import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {currentClinicContext,isClinicContext,encryptPrivate,sha256} from '../../../lib/clinic-runtime';
const reply=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(request:Request){try{const c=await currentClinicContext(request);if(!isClinicContext(c))return c;if(c.role!=='clinic_admin')return reply({error:'Clinic administrator access required'},403);const r=await c.db.prepare('SELECT whatsapp_phone_id,whatsapp_token_enc,whatsapp_app_secret_enc,verify_token_hash,whatsapp_enabled,api_enabled,api_key_hash FROM clinic_integrations WHERE clinic_id=?').bind(c.clinicId).first<Record<string,string|number|null>>();return reply({clinicId:c.clinicId,whatsapp:{phoneId:r?.whatsapp_phone_id??'',enabled:r?.whatsapp_enabled===1,configured:Boolean(r?.whatsapp_token_enc&&r?.whatsapp_app_secret_enc&&r?.verify_token_hash),webhookUrl:new URL('/api/whatsapp/webhook?clinic='+c.clinicId,request.url).href},api:{enabled:r?.api_enabled===1,configured:Boolean(r?.api_key_hash),url:new URL('/api/integrations/data?clinic='+c.clinicId+'&resource=services',request.url).href},ai:{configured:Boolean(env.OPENAI_API_KEY)}});}catch{return reply({error:'Could not load integration settings'},503);}}
export async function POST(request:Request){try{
 const c=await currentClinicContext(request);if(!isClinicContext(c))return c;if(c.role!=='clinic_admin')return reply({error:'Clinic administrator access required'},403);
 const d=z.object({action:z.enum(['whatsapp','rotate_api','disable_api']),phoneId:z.string().regex(/^\d{5,40}$/).optional(),token:z.string().max(4000).optional(),appSecret:z.string().max(500).optional(),verifyToken:z.string().max(200).optional(),enabled:z.boolean().optional()}).strict().parse(await request.json());
 let apiKey:string|undefined;
 if(d.action==='rotate_api'){apiKey='ayadati_'+crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');await c.db.prepare('INSERT INTO clinic_integrations (clinic_id,api_key_hash,api_enabled) VALUES (?,?,1) ON CONFLICT(clinic_id) DO UPDATE SET api_key_hash=excluded.api_key_hash,api_enabled=1').bind(c.clinicId,await sha256(apiKey)).run();}
 else if(d.action==='disable_api'){await c.db.prepare('UPDATE clinic_integrations SET api_enabled=0 WHERE clinic_id=?').bind(c.clinicId).run();}
 else{
  const old=await c.db.prepare('SELECT whatsapp_token_enc,whatsapp_app_secret_enc,verify_token_hash FROM clinic_integrations WHERE clinic_id=?').bind(c.clinicId).first<{whatsapp_token_enc:string|null;whatsapp_app_secret_enc:string|null;verify_token_hash:string|null}>();
  const token=d.token?.trim()?await encryptPrivate(d.token.trim()):old?.whatsapp_token_enc??null,secret=d.appSecret?.trim()?await encryptPrivate(d.appSecret.trim()):old?.whatsapp_app_secret_enc??null,verify=d.verifyToken?.trim()?await sha256(d.verifyToken.trim()):old?.verify_token_hash??null;
  if(d.enabled&&(!d.phoneId||!token||!secret||!verify))return reply({error:'Phone ID, access token, app secret and verification token are required'},400);
  await c.db.prepare('INSERT INTO clinic_integrations (clinic_id,whatsapp_phone_id,whatsapp_token_enc,whatsapp_app_secret_enc,verify_token_hash,whatsapp_enabled) VALUES (?,?,?,?,?,?) ON CONFLICT(clinic_id) DO UPDATE SET whatsapp_phone_id=excluded.whatsapp_phone_id,whatsapp_token_enc=excluded.whatsapp_token_enc,whatsapp_app_secret_enc=excluded.whatsapp_app_secret_enc,verify_token_hash=excluded.verify_token_hash,whatsapp_enabled=excluded.whatsapp_enabled,updated_at=CURRENT_TIMESTAMP').bind(c.clinicId,d.phoneId??null,token,secret,verify,d.enabled?1:0).run();
 }
 await c.db.prepare("INSERT INTO audit_logs (id,clinic_id,branch_id,actor_user_id,action,resource_type,resource_id) VALUES (?,?,?,?,'integration.updated','integrations',?)").bind(crypto.randomUUID(),c.clinicId,c.branchId,c.user.userId,d.action).run();return reply({ok:true,...(apiKey?{apiKey}:{})});
}catch(e){return reply({error:e instanceof z.ZodError?'Invalid integration settings':'Could not save integration settings; check that the phone ID is not assigned to another clinic'},e instanceof z.ZodError?400:503);}}
