import {z} from 'zod';
import {currentAccountContext,isAccountContext,currentClinicContext,isClinicContext,encryptPrivate,decryptPrivate,sha256} from '../../../../lib/clinic-runtime';
const reply=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function POST(request:Request){try{
 const c=await currentAccountContext(request);if(!isAccountContext(c))return c;
 const d=z.object({slug:z.string().regex(/^[a-z0-9][a-z0-9-]{1,47}[a-z0-9]$/),name:z.string().trim().min(2).max(160),phone:z.string().trim().min(5).max(40),service:z.string().trim().min(1).max(120),preferredDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v),notes:z.string().max(1000).default(''),requestKey:z.string().uuid()}).strict().parse(await request.json());
 if(Date.parse(d.preferredDate+'T23:59:59Z')<Date.now())return reply({error:'Choose a future date'},400);
 const clinic=await c.db.prepare('SELECT id FROM clinics WHERE public_slug=? AND public_enabled=1').bind(d.slug).first<{id:string}>();if(!clinic)return reply({error:'Clinic not found'},404);
 const prior=await c.db.prepare('SELECT id,clinic_id FROM public_booking_requests WHERE user_id=? AND request_key=?').bind(c.user.userId,d.requestKey).first<{id:string;clinic_id:string}>();if(prior)return prior.clinic_id===clinic.id?reply({id:prior.id,status:'pending'}):reply({error:'Request key reused'},409);
 const id=crypto.randomUUID(),today=new Date().toISOString().slice(0,10),hash=await sha256(c.user.email.toLowerCase());
 const saved=await c.db.prepare("INSERT OR IGNORE INTO public_booking_requests (id,clinic_id,user_id,email_hash,data_enc,request_key) SELECT ?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM public_booking_requests WHERE user_id=? AND substr(created_at,1,10)=?)<5").bind(id,clinic.id,c.user.userId,hash,await encryptPrivate(JSON.stringify({...d,email:c.user.email})),d.requestKey,c.user.userId,today).run();
 return saved.meta.changes?reply({id,status:'pending'},201):reply({error:'Daily request limit reached; contact the clinic'},429);
}catch(e){return reply({error:e instanceof z.ZodError?'Check the booking details':'Could not submit the booking request'},e instanceof z.ZodError?400:503);}}
export async function GET(request:Request){try{const c=await currentClinicContext(request);if(!isClinicContext(c))return c;if(!['clinic_admin','receptionist','doctor'].includes(c.role))return reply({error:'Access denied'},403);const rows=(await c.db.prepare('SELECT id,status,data_enc,created_at FROM public_booking_requests WHERE clinic_id=? ORDER BY created_at DESC LIMIT 200').bind(c.clinicId).all<{id:string;status:string;data_enc:string;created_at:string}>()).results;return reply({rows:await Promise.all(rows.map(async r=>({id:r.id,status:r.status,createdAt:r.created_at,...JSON.parse(await decryptPrivate(r.data_enc))})))});}catch{return reply({error:'Could not load booking requests'},503);}}
export async function PATCH(request:Request){try{const c=await currentClinicContext(request);if(!isClinicContext(c))return c;if(!['clinic_admin','receptionist','doctor'].includes(c.role))return reply({error:'Access denied'},403);const d=z.object({id:z.string().uuid(),status:z.enum(['contacted','rejected'])}).strict().parse(await request.json());const result=await c.db.batch([c.db.prepare("UPDATE public_booking_requests SET status=? WHERE id=? AND clinic_id=? AND status IN ('pending','contacted')").bind(d.status,d.id,c.clinicId),c.db.prepare("INSERT INTO audit_logs (id,clinic_id,branch_id,actor_user_id,action,resource_type,resource_id) SELECT ?,?,?,?,'booking.reviewed','booking_requests',? WHERE changes()>0").bind(crypto.randomUUID(),c.clinicId,c.branchId,c.user.userId,d.id)]);return result[0].meta.changes?reply({ok:true}):reply({error:'Request no longer available'},409);}catch(e){return reply({error:'Could not update request'},e instanceof z.ZodError?400:503);}}
