"use client";
import {useEffect,useState} from "react";
import {ExternalLink,Globe2,Save,Search} from "lucide-react";
import {authFetch} from "./auth-client";
type Language="ar"|"he"|"en";
const copy={
 ar:{title:"موقع العيادة العام",desc:"أنشئ صفحة تعريفية للعيادة ضمن نطاق البرنامج. لا تعرض الصفحة أي معلومات عن المرضى.",slug:"اسم الرابط (بالإنجليزية)",description:"نبذة عن العيادة",seoTitle:"عنوان الظهور في Google",seoDescription:"وصف النتيجة في Google",phone:"هاتف الاستفسار",address:"العنوان",booking:"رابط الحجز أو WhatsApp (HTTPS)",enable:"نشر الصفحة العامة",save:"حفظ الموقع",loading:"جارٍ تحميل الإعدادات…",done:"تم حفظ إعدادات الموقع",error:"تعذر حفظ الإعدادات. تأكد أن اسم الرابط غير مستخدم.",preview:"معاينة صفحة العيادة",available:"يظهر رابط الصفحة بعد حفظها ونشرها.",searchPreview:"معاينة نتيجة البحث",searchHint:"اكتب عنوانًا ووصفًا يوضحان اسم العيادة وخدماتها وموقعها. تجنب تكرار الكلمات.",titleLimit:"حتى 70 حرفًا",descriptionLimit:"حتى 180 حرفًا"},
 he:{title:"האתר הציבורי של המרפאה",desc:"צרו עמוד מידע למרפאה בדומיין הפלטפורמה. מידע על מטופלים לא מוצג בו.",slug:"שם קישור (באנגלית)",description:"אודות המרפאה",seoTitle:"כותרת לתוצאת Google",seoDescription:"תיאור בתוצאת Google",phone:"טלפון לבירורים",address:"כתובת",booking:"קישור לקביעת תור או WhatsApp (HTTPS)",enable:"פרסום העמוד הציבורי",save:"שמירת האתר",loading:"טוען הגדרות…",done:"הגדרות האתר נשמרו",error:"לא ניתן לשמור. בדקו אם שם הקישור פנוי.",preview:"תצוגת עמוד המרפאה",available:"הקישור יופיע לאחר שמירת הפרסום.",searchPreview:"תצוגת תוצאת חיפוש",searchHint:"כתבו כותרת ותיאור שמסבירים את שם המרפאה, שירותיה ומיקומה.",titleLimit:"עד 70 תווים",descriptionLimit:"עד 180 תווים"},
 en:{title:"Public clinic website",desc:"Publish a clinic information page under the platform domain. It never displays patient information.",slug:"URL name (English letters)",description:"About the clinic",seoTitle:"Google search title",seoDescription:"Google search description",phone:"Contact phone",address:"Address",booking:"Booking or WhatsApp link (HTTPS)",enable:"Publish public page",save:"Save website",loading:"Loading settings…",done:"Website settings saved",error:"Could not save. The URL name may already be in use.",preview:"Preview clinic page",available:"The page link appears after publishing.",searchPreview:"Search result preview",searchHint:"Write a clear title and description that describe the clinic and its location.",titleLimit:"Up to 70 characters",descriptionLimit:"Up to 180 characters"}
} satisfies Record<Language,Record<string,string>>;
type Website={slug:string;description:string;seoTitle:string;seoDescription:string;phone:string;address:string;bookingUrl:string;enabled:boolean};
const empty:Website={slug:"",description:"",seoTitle:"",seoDescription:"",phone:"",address:"",bookingUrl:"",enabled:false};
export default function ClinicWebsiteSettings({lang}:{lang:Language}){
 const t=copy[lang];const [clinicName,setClinicName]=useState("");const [data,setData]=useState<Website>(empty);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [url,setUrl]=useState("");
 useEffect(()=>{let active=true;void authFetch("/api/clinic-website").then(async r=>{const d=await r.json() as {clinicName?:string;website?:Record<string,unknown>};if(active&&r.ok){const w=d.website??{};setClinicName(d.clinicName??"");setData({slug:String(w.public_slug??""),description:String(w.public_description??""),seoTitle:String(w.public_seo_title??""),seoDescription:String(w.public_seo_description??""),phone:String(w.public_phone??""),address:String(w.public_address??""),bookingUrl:String(w.public_booking_url??""),enabled:w.public_enabled===1||w.public_enabled===true});}}).catch(()=>{if(active)setMessage(t.error);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[t.error]);
 function update<K extends keyof Website>(key:K,value:Website[K]){setData(current=>({...current,[key]:value}));}
 async function save(){setBusy(true);setMessage("");try{const r=await authFetch("/api/clinic-website",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),d=await r.json() as {error?:string;url?:string|null};if(!r.ok)throw new Error(d.error??t.error);setUrl(d.url??"");setMessage(t.done);}catch(e){setMessage(e instanceof Error?e.message:t.error);}finally{setBusy(false);}}
 const resultTitle=data.seoTitle||`${clinicName||"عيادتي"} | عيادتي`;const resultDescription=data.seoDescription||data.description||t.desc;
 return <section className="panel clinic-website-settings"><div className="panel-heading"><div><h2><Globe2 size={19}/>{t.title}</h2><p>{t.desc}</p></div></div>{loading?<p>{t.loading}</p>:<><div className="ops-fields"><label className="form-label">{t.slug}<span className="slug-input"><span>/c/</span><input dir="ltr" value={data.slug} onChange={e=>update("slug",e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} maxLength={48} placeholder="my-clinic"/></span></label><label className="form-label">{t.phone}<input dir="ltr" value={data.phone} onChange={e=>update("phone",e.target.value)} maxLength={40}/></label><label className="form-label ops-wide">{t.description}<textarea value={data.description} onChange={e=>update("description",e.target.value)} maxLength={2500}/></label><label className="form-label">{t.address}<input value={data.address} onChange={e=>update("address",e.target.value)} maxLength={300}/></label><label className="form-label">{t.booking}<input dir="ltr" type="url" value={data.bookingUrl} onChange={e=>update("bookingUrl",e.target.value)} maxLength={300} placeholder="https://wa.me/970..."/></label></div>
 <div className="clinic-seo-fields"><div className="clinic-seo-heading"><h3><Search size={18}/>{lang==="ar"?"تحسين ظهور العيادة في البحث":lang==="he"?"שיפור הנראות בחיפוש":"Improve search visibility"}</h3><p>{t.searchHint}</p></div><label className="form-label">{t.seoTitle}<input value={data.seoTitle} onChange={e=>update("seoTitle",e.target.value)} maxLength={70} placeholder={clinicName||"عيادة النور | طب الأسنان"}/><small>{data.seoTitle.length} / 70 · {t.titleLimit}</small></label><label className="form-label">{t.seoDescription}<textarea value={data.seoDescription} onChange={e=>update("seoDescription",e.target.value)} maxLength={180} placeholder={data.description.slice(0,120)||t.searchHint}/><small>{data.seoDescription.length} / 180 · {t.descriptionLimit}</small></label><article className="seo-search-preview" dir={lang==="en"?"ltr":"rtl"}><h4>{t.searchPreview}</h4><b>{resultTitle}</b><span>clinic-ops-palestine.nbeelsalah4.chatgpt.site/c/{data.slug||"my-clinic"}</span><p>{resultDescription}</p></article></div>
 <label className="website-publish"><input type="checkbox" checked={data.enabled} onChange={e=>update("enabled",e.target.checked)}/>{t.enable}</label><div className="verification-actions"><button className="button button-primary" disabled={busy} onClick={()=>void save()}><Save size={16}/>{t.save}</button>{url&&<a className="button button-outline" href={url} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{t.preview}</a>}</div>{message&&<p className="subscriber-notice" role="status">{message}</p>}{!url&&<small className="website-hint">{clinicName} · {t.available}</small>}</>}</section>;
}
