"use client";

import { useEffect, useState } from "react";
import { Activity, CalendarDays, Check, FileHeart, Globe2, HeartPulse, Languages, LockKeyhole, ShieldCheck, Sparkles, Users, WalletCards } from "lucide-react";
import { AuthScreen } from "./auth-screen";
import type { LucideIcon } from "lucide-react";

type Language="ar"|"he"|"en";
type MarketingCopy={tag:string;headline:string;lead:string;start:string;trial:string;login:string;featuresTitle:string;featuresSub:string;features:[LucideIcon,string,string][];plansTitle:string;monthly:string;annual:string;choose:string;trialText:string;plans:[string,string,number,string,string[]][];pay:string;currency:string;more:string;footer:string;language:string;loginTitle:string;loginSub:string};
const content:Record<Language,MarketingCopy>={
 ar:{tag:"منصة عيادتي الصحية",headline:"من أول موعد، إلى آخر متابعة",lead:"نظّم يوم فريقك، اجمع السجل الطبي، وتابع التحصيل والتأمين والجلسات من منصة واحدة للعيادات والمراكز الصحية في فلسطين.",start:"ابدأ الآن",trial:"اطلب شهرًا مجانيًا",login:"دخول العيادة",featuresTitle:"أدوات يومية لعمل صحي أكثر تنظيمًا",featuresSub:"إدارة آمنة وسهلة من الكمبيوتر أو الهاتف.",features:[[Users,"ملفات المرضى","سجل موحد للمرضى والزيارات والمرفقات الطبية."],[CalendarDays,"المواعيد والفريق","تنظيم جداول الأطباء والفروع والموظفين."],[WalletCards,"الفواتير والتحصيل","متابعة الدفعات والديون والتقارير بعملة الشيقل."],[FileHeart,"الوصفات والمختبر","وصفات طبية وسجلات للفحوصات والنتائج."],[Globe2,"موقع لكل عيادة","أنشئ صفحة عامة باسم عيادتك على نطاق المنصة."],[ShieldCheck,"خصوصية وصلاحيات","حسابات منفصلة للعيادات وصلاحيات حسب دور الموظف."]],plansTitle:"خطط تناسب حجم عيادتك",monthly:"شهريًا",annual:"سنويًا",choose:"اختر هذه الخطة",trialText:"30 يومًا مجانًا بعد مراجعة الطلب. لا نطلب بطاقة دفع للتجربة.",plans:[["starter","البداية",49,"لعيادة مستقلة تريد تنظيم عملها اليومي",["ملفات المرضى والزيارات والمواعيد","فواتير ومدفوعات وتقارير أساسية","بحث سريع وواجهة بثلاث لغات"]],["professional","احترافية",99,"لفريق طبي متعدد التخصصات",["كل مزايا البداية","إدارة الفروع والأطباء والموظفين والصلاحيات","وصفات طبية مع أدوية شائعة وإضافة دواء بالكتابة","سجلات المختبر ونتائج الفحوصات"]],["business","الأعمال",179,"لعيادات تنمو وتدير خدمات ومخزونًا",["كل مزايا احترافية","مخزون الأدوية والتنبيه للكميات والصلاحية","الموردون والمشتريات والمصروفات","صفحة عامة مستقلة باسم العيادة"]],["medical_center","مركز طبي",299,"للمراكز التي تنسق عدة فروع",["كل مزايا الأعمال","ربط الفروع وإدارة التشغيل عبرها","تقارير مالية وتشغيلية موسعة","التأمين والمطالبات والعمولات والباقات"]]],pay:"الدفع الإلكتروني عبر Qredit",currency:"₪ شيقل إسرائيلي",more:"الأسعار المعروضة رسوم الاشتراك؛ تواصل معنا لخطة المؤسسات متعددة المواقع.",footer:"عيادتي — إدارة صحية واضحة وآمنة",language:"اللغة",loginTitle:"تابع إلى حسابك",loginSub:"أنشئ حسابًا لتطلب التجربة أو تفعّل اشتراك عيادتك."},
 he:{tag:"פלטפורמת עיאדתי לבריאות",headline:"מהתור הראשון ועד למעקב",lead:"ניהול צוות, תיקים רפואיים, תשלומים, ביטוח ומפגשי טיפול במערכת אחת למרפאות בפלסטין.",start:"התחילו עכשיו",trial:"בקשת חודש ניסיון",login:"כניסה למרפאה",featuresTitle:"כלים יומיומיים לעבודה מסודרת",featuresSub:"ניהול מאובטח מהמחשב או מהטלפון.",features:[[Users,"תיקי מטופלים","מטופלים, ביקורים ומסמכים רפואיים במקום אחד."],[CalendarDays,"תורים וצוות","ניהול יומני רופאים, סניפים ועובדים."],[WalletCards,"חשבוניות וגבייה","מעקב תשלומים, חובות ודוחות בשקלים."],[FileHeart,"מרשמים ומעבדה","מרשמים רפואיים, בדיקות ותוצאות."],[Globe2,"אתר לכל מרפאה","עמוד ציבורי למרפאה בדומיין הפלטפורמה."],[ShieldCheck,"פרטיות והרשאות","חשבונות מופרדים והרשאות לפי תפקיד."]],plansTitle:"תוכניות לכל גודל מרפאה",monthly:"לחודש",annual:"לשנה",choose:"בחירת תוכנית",trialText:"30 יום ללא תשלום לאחר בדיקת הבקשה. ללא כרטיס אשראי.",plans:[["starter","התחלה",49,"למרפאה עצמאית שרוצה סדר בעבודה היומיומית",["תיקי מטופלים, ביקורים ותורים","חשבוניות, תשלומים ודוחות בסיסיים","חיפוש מהיר וממשק בשלוש שפות"]],["professional","מקצועית",99,"לצוות רפואי רב תחומי",["כל תכונות ההתחלה","ניהול סניפים, רופאים, עובדים והרשאות","מרשמים עם תרופות נפוצות והוספה חופשית","רישומי מעבדה ותוצאות בדיקות"]],["business","עסקית",179,"למרפאות בצמיחה עם שירותים ומלאי",["כל תכונות המקצועית","מלאי תרופות והתראות על כמות ותפוגה","ספקים, רכש והוצאות","עמוד ציבורי ייעודי למרפאה"]],["medical_center","מרכז רפואי",299,"למרכזים המתאמים מספר סניפים",["כל תכונות העסקית","קישור סניפים וניהול הפעילות ביניהם","דוחות כספיים ותפעוליים מורחבים","תביעות ביטוח, עמלות וחבילות"]]],pay:"תשלום מאובטח דרך Qredit",currency:"₪ שקל ישראלי",more:"המחירים הם דמי מנוי; פנו אלינו לתוכנית ארגונית למספר אתרים.",footer:"עיאדתי — ניהול בריאות ברור ומאובטח",language:"שפה",loginTitle:"המשיכו לחשבון",loginSub:"צרו חשבון כדי לבקש ניסיון או להפעיל מנוי."},
 en:{tag:"Ayadati clinic platform",headline:"From first appointment to follow-up",lead:"Coordinate your team, keep clinical records together, and track payments, insurance and treatment sessions in one clinic platform.",start:"Get started",trial:"Request a free month",login:"Clinic sign in",featuresTitle:"Everyday tools for a more organized clinic",featuresSub:"Manage securely from desktop or phone.",features:[[Users,"Patient records","Keep patient visits and medical files together."],[CalendarDays,"Appointments & team","Coordinate doctor schedules, branches and staff."],[WalletCards,"Billing & payments","Track payments, balances and ILS reports."],[FileHeart,"Prescriptions & lab","Create prescriptions and manage test results."],[Globe2,"A website for each clinic","Publish a clinic page on the platform domain."],[ShieldCheck,"Privacy & access","Separate clinic accounts and role based access."]],plansTitle:"Plans for clinics of every size",monthly:"per month",annual:"per year",choose:"Choose plan",trialText:"30 days free after request review. No payment card required.",plans:[["starter","Starter",49,"For an independent clinic organizing daily work",["Patient profiles, visits and appointments","Invoices, payments and basic reports","Quick search and a three-language interface"]],["professional","Professional",99,"For a multidisciplinary care team",["Everything in Starter","Branches, doctors, staff and role permissions","Prescriptions with common medicines and free text entry","Lab records and test results"]],["business","Business",179,"For growing clinics managing services and stock",["Everything in Professional","Medicine inventory with quantity and expiry alerts","Suppliers, purchasing and expenses","A public page for your clinic"]],["medical_center","Medical center",299,"For centers coordinating multiple branches",["Everything in Business","Link branches and manage operations across them","Expanded financial and operational reports","Insurance claims, commissions and packages"]]],pay:"Online payment with Qredit",currency:"₪ Israeli shekel",more:"Prices are subscription fees. Contact us for a multi-site enterprise plan.",footer:"Ayadati — clear, secure clinic management",language:"Language",loginTitle:"Continue to your account",loginSub:"Create an account to request a trial or activate a subscription."}
};

export default function MarketingSite({lang,onLanguageChange}:{lang:Language;onLanguageChange:(lang:Language)=>void}){
 const t=content[lang],rtl=lang!=='en';const [authMode,setAuthMode]=useState<"signup"|"signin"|null>(null);
 useEffect(()=>{const plan=new URLSearchParams(window.location.search).get("plan");if(plan&&["starter","professional","business","medical_center"].includes(plan))localStorage.setItem("clinic-selected-plan",plan);},[]);
 if(authMode)return <div dir={rtl?"rtl":"ltr"}><button className="marketing-back" onClick={()=>setAuthMode(null)}>{lang==='ar'?"العودة إلى الموقع":lang==='he'?"חזרה לאתר":"Back to website"}</button><AuthScreen lang={lang} onLanguageChange={onLanguageChange} initialMode={authMode}/></div>;
 return <main className="marketing-page" dir={rtl?"rtl":"ltr"}>
  <header className="marketing-nav"><a href="#top" className="marketing-brand"><span><HeartPulse size={23}/></span><b>عيادتي</b></a><nav><a href="/patient">{lang==='ar'?"بوابة المريض":lang==='he'?"פורטל מטופל":"Patient portal"}</a><a href="#features">{lang==='ar'?"الخدمات":lang==='he'?"שירותים":"Services"}</a><a href="#plans">{lang==='ar'?"الخطط":lang==='he'?"תוכניות":"Plans"}</a></nav><div className="marketing-tools"><button className="marketing-language" onClick={()=>onLanguageChange(lang==='ar'?'he':lang==='he'?'en':'ar')} aria-label={t.language}><Languages size={17}/>{lang.toUpperCase()}</button><button className="marketing-login" onClick={()=>setAuthMode("signin")}>{t.login}</button></div></header>
  <section id="top" className="marketing-hero"><div className="marketing-hero-copy"><span className="marketing-eyebrow"><Sparkles size={15}/>{t.tag}</span><h1>{t.headline}</h1><p>{t.lead}</p><div className="marketing-actions"><button className="marketing-primary" onClick={()=>setAuthMode("signup")}>{t.start}</button><button className="marketing-secondary" onClick={()=>setAuthMode("signup")}>{t.trial}</button></div><small className="marketing-trial-note"><Check size={14}/>{t.trialText}</small></div><div className="marketing-preview"><div className="preview-top"><span className="preview-logo"><HeartPulse size={20}/></span><span>{lang==='ar'?"ملخص العيادة":lang==='he'?"סקירת המרפאה":"Clinic overview"}</span><small className="preview-demo-label">{lang==='ar'?"مثال توضيحي":lang==='he'?"נתוני דוגמה":"Illustrative data"}</small></div><div className="preview-greeting">{lang==='ar'?"صباح الخير 👋":lang==='he'?"בוקר טוב 👋":"Good morning 👋"}<b>{lang==='ar'?"إليك نشاط عيادتك اليوم":lang==='he'?"הפעילות היומית שלך":"Here is today's clinic activity"}</b></div><div className="preview-stats"><div><Users/><strong>248</strong><small>{lang==='ar'?"مريض":lang==='he'?"מטופלים":"Patients"}</small></div><div><CalendarDays/><strong>18</strong><small>{lang==='ar'?"موعد اليوم":lang==='he'?"תורים היום":"Today's visits"}</small></div><div><Activity/><strong>₪ 2,450</strong><small>{lang==='ar'?"التحصيل اليوم":lang==='he'?"הכנסות היום":"Collected today"}</small></div></div><div className="preview-line"><span/>{lang==='ar'?"بيانات منفصلة لكل عيادة ومشفرة":lang==='he'?"נתונים מוצפנים ונפרדים לכל מרפאה":"Encrypted data, separated by clinic"}<ShieldCheck size={15}/></div></div><div className="marketing-orb marketing-orb-one"/><div className="marketing-orb marketing-orb-two"/></section>
  <section id="features" className="marketing-features"><div className="marketing-section-title"><span>{lang==='ar'?"منصة واحدة، تفاصيل أقل":lang==='he'?"מערכת אחת, פחות טרחה":"One platform, less busywork"}</span><h2>{t.featuresTitle}</h2><p>{t.featuresSub}</p></div><div className="marketing-feature-grid">{t.features.map(([Icon,title,desc],i)=><article className="marketing-feature" key={title}><span className={`feature-icon feature-${i}`}><Icon size={21}/></span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>

  <section className="marketing-operations"><div className="marketing-section-title"><span>{lang==='ar'?'من الاستقبال إلى الإدارة':lang==='he'?'מהקבלה ועד לניהול':'From reception to management'}</span><h2>{lang==='ar'?'تفاصيل العمل مترابطة':lang==='he'?'כל פרטי העבודה מחוברים':'Keep every part of care connected'}</h2></div><div className="marketing-operation-grid">{(lang==='ar'?[
 ['01','استقبال أكثر تنظيمًا','ملفات المرضى، جداول الأطباء وقائمة انتظار لمتابعة فرص المواعيد الملغاة.'],
 ['02','سجل يناسب التخصص','سجلات مستقلة للأسنان والأطفال والنسائية والعيون والجلدية والعلاج الطبيعي، مع مخطط الأسنان والقياسات والتطعيمات وصور قبل/بعد.'],
 ['03','متابعة مالية أوضح','الفواتير والتحصيل والمصروفات، وسجلات مطالبات التأمين وعمولات الأطباء وأرصدة الباقات.']
 ]:lang==='he'?[
 ['01','קבלה מסודרת','תיקי מטופלים, יומני רופאים ורשימת המתנה למעקב אחר תורים שבוטלו.'],
 ['02','תיעוד לפי מומחיות','תבניות לשיניים, ילדים, נשים, עיניים, עור ופיזיותרפיה, עם מרשמים וקבצים והסכמות.'],
 ['03','מעקב כספי ברור','חשבוניות, גבייה והוצאות, רשומות תביעות ביטוח, עמלות ויתרות חבילות.']
 ]:[
 ['01','Organized reception','Patient profiles, doctor schedules and a waitlist to follow up on cancelled slots.'],
 ['02','Records for your specialty','Dedicated dental, pediatric, obstetric, eye, skin and physiotherapy records, including tooth charts, measurements, vaccinations and before/after images.'],
 ['03','Clear financial follow-up','Billing, collections and expenses alongside insurance claim records, doctor commissions and package balances.']
 ]).map(([number,title,desc])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
  <section id="plans" className="marketing-plans"><div className="marketing-section-title"><span>{lang==='ar'?"واضحة ومرنة":lang==='he'?"ברור וגמיש":"Clear and flexible"}</span><h2>{t.plansTitle}</h2><p>{t.pay} · {t.currency}</p></div><div className="marketing-plan-grid">{t.plans.map(([id,name,price,audience,benefits],i)=><article className={`marketing-plan ${i===1?'plan-featured':''}`} key={id}>{i===1&&<span className="plan-popular">{lang==='ar'?"الأكثر اختيارًا":lang==='he'?"הנבחרת ביותר":"Most popular"}</span>}<h3>{name}</h3><p className="plan-price"><b>{price}</b><span>₪ / {t.monthly}</span></p><small>{lang==='ar'?"أو ":lang==='he'?"או ":"or "}{price*10} ₪ / {t.annual}</small><p className="plan-audience">{audience}</p><ul>{benefits.map((benefit,index)=><li key={index}><Check size={15}/>{benefit}</li>)}</ul><button onClick={()=>{localStorage.setItem("clinic-selected-plan",id);setAuthMode("signup");}}>{t.choose}</button></article>)}</div><p className="marketing-plan-note">{t.more}</p><button className="marketing-trial-cta" onClick={()=>setAuthMode("signup")}><LockKeyhole size={17}/>{t.trial}</button></section>

  <section className="marketing-faq"><div><span className="marketing-eyebrow">{lang==='ar'?'قبل أن تبدأ':lang==='he'?'לפני שמתחילים':'Before you start'}</span><h2>{lang==='ar'?'إجابات واضحة':lang==='he'?'תשובות ברורות':'Straightforward answers'}</h2></div><div>{(lang==='ar'?[
 ['كيف أبدأ التجربة المجانية؟','أنشئ حسابًا وقدم طلب تجربة. بعد مراجعة الطلب تحصل على 30 يومًا دون بطاقة دفع.'],
 ['هل أحتاج تثبيت برنامج؟','تعمل المنصة من المتصفح على الكمبيوتر والهاتف. تحتاج اتصالًا بالإنترنت.'],
 ['هل يمكن لكل موظف الدخول بحسابه؟','نعم، تدعم المنصة حسابات الفريق وصلاحيات الطبيب والتمريض والاستقبال والمحاسب، مع إدارة مستقلة للمنصة.'],
 ['هل المطالبات ترسل تلقائيًا للتأمين؟','يمكنك تسجيل المطالبات والموافقات والتسويات. إرسالها لشركات التأمين يتم خارج المنصة حاليًا.'],
 ['هل WhatsApp والذكاء الاصطناعي متاحان الآن؟','أدوات الربط موجودة: استقبال WhatsApp ومساعد توثيق الطبيب بالنص والصوت. تشغيلها يتطلب تهيئة اتصال Meta وOpenAI للمنصة.']
 ]:lang==='he'?[
 ['איך מתחילים ניסיון?','צרו חשבון והגישו בקשה. לאחר בדיקה מקבלים 30 יום ללא כרטיס תשלום.'],
 ['צריך להתקין תוכנה?','המערכת פועלת בדפדפן במחשב ובטלפון עם חיבור לאינטרנט.'],
 ['לכל עובד יש חשבון?','כן, עם הרשאות לרופא, סיעוד, קבלה וחשבונאות וניהול פלטפורמה נפרד.'],
 ['תביעות נשלחות אוטומטית?','ניתן לתעד תביעות, אישורים ותשלומים. ההגשה למבטח מתבצעת כרגע מחוץ למערכת.'],
 ['האם WhatsApp ו-AI פעילים?','כלי קבלת WhatsApp ותיעוד רפואי בטקסט ואודיו מוכנים לחיבור. להפעלה נדרשת הגדרת Meta ו-OpenAI.']
 ]:[
 ['How does the trial work?','Create an account and submit a request. Once reviewed, your clinic receives 30 days without a payment card.'],
 ['Do I install any software?','Use your browser on desktop or mobile with an internet connection.'],
 ['Can each employee have an account?','Yes, with doctor, nursing, reception and accountant permissions, separate from platform administration.'],
 ['Are insurance claims sent automatically?','Track claims, approvals and settlements here. Submission to insurers currently happens outside the platform.'],
 ['Are WhatsApp and AI live?','WhatsApp reception and text/audio clinical documentation tools are ready for provider connections. They require Meta and OpenAI configuration to run.']
 ]).map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <footer className="marketing-footer"><span className="marketing-brand"><span><HeartPulse size={20}/></span><b>عيادتي</b></span><span>{t.footer} · © {new Date().getFullYear()}</span></footer>
 </main>;
}
