'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {supabase} from './auth-client';
import {ShieldCheck} from 'lucide-react';
import type {Language} from '../lib/ops-model';
type Factor={id:string;friendly_name?:string;status:string};
export function MfaPanel({lang}:{lang:Language}){
 const [factors,setFactors]=useState<Factor[]>([]),[enrollment,setEnrollment]=useState<{id:string;qr:string;secret:string}|null>(null),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const t=(ar:string,he:string,en:string)=>lang==='ar'?ar:lang==='he'?he:en;
 async function load(){const {data,error}=await supabase.auth.mfa.listFactors();if(error)throw error;setFactors(data.all.filter(f=>f.factor_type==='totp'));}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:String(e)));},[]);
 async function enroll(){setBusy(true);setError('');try{const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Ayadati-'+Date.now()});if(error)throw error;setEnrollment({id:data.id,qr:data.totp.qr_code,secret:data.totp.secret});await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function verify(){if(!enrollment)return;setBusy(true);setError('');try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:enrollment.id,code});if(error)throw error;setEnrollment(null);setCode('');await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function remove(id:string){if(!window.confirm(t('إلغاء وسيلة المصادقة هذه؟','לבטל אמצעי אימות זה?','Remove this authentication factor?')))return;setBusy(true);setError('');try{const {error}=await supabase.auth.mfa.unenroll({factorId:id});if(error)throw error;if(enrollment?.id===id)setEnrollment(null);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <section className="panel clinic-settings-panel"><div className="panel-heading"><h2><ShieldCheck size={20}/>{t('المصادقة الثنائية 2FA','אימות דו-שלבי','Two-factor authentication')}</h2></div><p>{t('اربط تطبيق رموز مثل Google Authenticator. بعد التفعيل سيُطلب الرمز عند تسجيل الدخول، بالإضافة إلى كلمة المرور أو الدخول الاجتماعي.','חברו אפליקציית אימות כמו Google Authenticator. לאחר הפעלה יידרש קוד בכניסה בנוסף לסיסמה או כניסה חברתית.','Connect an authenticator app such as Google Authenticator. Once enabled, sign-in requires its code in addition to your password or social sign-in.')}</p>{factors.map(f=><div className="ops-summary-row" key={f.id}><span>{f.friendly_name??'Authenticator'} · {f.status==='verified'?t('مفعّل','פעיל','Enabled'):t('بانتظار التأكيد','ממתין לאישור','Pending confirmation')}</span><button className="button button-outline" disabled={busy} onClick={()=>void remove(f.id)}>{t('إلغاء','ביטול','Remove')}</button></div>)}{enrollment?<div className="mfa-enrollment"><p>{t('امسح الرمز بتطبيق المصادقة ثم أدخل الرمز المكوّن من 6 أرقام لتأكيد التفعيل.','סרקו באפליקציית האימות והזינו קוד בן 6 ספרות לאישור.','Scan in your authenticator app, then enter its six-digit code to confirm enrollment.')}</p><img src={enrollment.qr.startsWith('data:')?enrollment.qr:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(enrollment.qr)} width={220} height={220} alt={t('رمز ربط تطبيق المصادقة','קוד חיבור אפליקציית אימות','Authenticator enrollment QR code')}/><label className="form-label">{t('مفتاح الإعداد اليدوي','מפתח להגדרה ידנית','Manual setup key')}<input readOnly dir="ltr" value={enrollment.secret}/></label><label className="form-label">{t('رمز التطبيق','קוד אפליקציה','Authenticator code')}<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="button button-primary" disabled={busy||code.length!==6} onClick={()=>void verify()}>{t('تأكيد التفعيل','אישור הפעלה','Confirm enrollment')}</button></div>:<button className="button button-outline" disabled={busy} onClick={()=>void enroll()}>{t('إضافة تطبيق مصادقة','הוספת אפליקציית אימות','Add authenticator')}</button>}{error&&<p className="error-banner" role="alert">{error}</p>}</section>;
}
export function MfaGate({children}:{children:ReactNode}){
 const [version,setVersion]=useState(0),[ready,setReady]=useState(false),[factorId,setFactorId]=useState<string|null>(null),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const {data}=supabase.auth.onAuthStateChange(()=>setVersion(v=>v+1));return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{let active=true;setReady(false);void (async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){if(active){setFactorId(null);setError('');setReady(true);}return;}const [assurance,factors]=await Promise.all([supabase.auth.mfa.getAuthenticatorAssuranceLevel(),supabase.auth.mfa.listFactors()]);if(assurance.error)throw assurance.error;if(factors.error)throw factors.error;const factor=factors.data.totp.find(f=>f.status==='verified');if(active){setFactorId(factor&&assurance.data.currentLevel!=='aal2'?factor.id:null);setError('');setReady(true);}})().catch(e=>{if(active){setError(e instanceof Error?e.message:String(e));setReady(true);}});return()=>{active=false;};},[version]);
 async function verify(e:React.FormEvent){e.preventDefault();if(!factorId)return;setBusy(true);setError('');try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId,code});if(error)throw error;setCode('');setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 if(!ready)return <div className="site-loading"/>;
 if(!factorId&&!error)return children;
 return <main className="portal-page" dir="rtl"><div className="portal-content"><section className="panel booking-public"><h1>تأكيد الدخول بخطوتين</h1><p>أدخل رمز تطبيق المصادقة للمتابعة إلى حسابك. / Enter your authenticator code.</p>{factorId&&<form onSubmit={verify}><label className="form-label">رمز التطبيق / Authenticator code<input required inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="button button-primary" disabled={busy||code.length!==6}>تحقق / Verify</button></form>}{error&&<p className="error-banner" role="alert">{error}</p>}<button className="button button-outline" disabled={busy} onClick={()=>void supabase.auth.signOut()}>تسجيل الخروج / Sign out</button>{error&&<button className="button button-outline" onClick={()=>setVersion(v=>v+1)}>إعادة المحاولة / Retry</button>}</section></div></main>;
}
