"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import type { Session } from "@supabase/supabase-js";
import { authFetch, authReturn, supabase } from "./auth-client";
import VerificationPanel from "./verification-panel";
import { EmailSettingsPanel,TrialAdminPanel,TrialRequestPanel } from "./subscriber-panels";
import {QueuePanel,PortalAccessPanel,BookingRequestsPanel} from "./operations-tools";
import {MfaPanel} from "./mfa-panel";
import IntegrationsPanel from "./integrations-panel";
import SpecialtyWorkspace from "./specialty-workspace";
import ClinicWorkspace,{opsText} from "./clinic-workspace";
import {canAccess} from "../lib/ops-model";
import ProgramDashboard from "./program-dashboard";
import { AuthScreen } from "./auth-screen";
import MarketingSite from "./marketing-site";
import SubscriptionCheckoutPanel from "./subscription-checkout-panel";
import ClinicWebsiteSettings from "./clinic-website-settings";
import ClinicSettingsPanel from "./clinic-settings-panel";
import {
  Activity, Bell, CalendarDays, Check,
  ChevronDown, ChevronLeft, Clock3,
  FileText, FlaskConical, HeartPulse, KeyRound, Languages, LayoutDashboard,
  Menu, Moon, Package, Plus, Search, Settings2, ShieldCheck,
  Stethoscope, Sun, UserRound, Users, WalletCards, X,
} from "lucide-react";

type Language = "ar" | "he" | "en";
type Section = "feedback" | "payroll" | "queue" | "portal_access" | "booking_requests" | "insurance" | "waitlist" | "packages" | "commissions" | "consents" | "complaints" | "specialty" | "dashboard" | "patients" | "appointments" | "doctors" | "billing" | "reports" | "inventory" | "lab" | "licenses" | "settings" | "visits" | "prescriptions" | "branches" | "suppliers" | "expenses" | "attendance" | "services" | "users" | "files" | "audit" | "notifications";
type Patient = { name: string; id: string; patientId: string; phone: string; doctor: string; lastVisit: string; status: "جديد" | "متابعة" | "مكتمل" };
type Appointment = { id: string; time: string; name: string; type: string; doctor: string; tone: string; status: "قادم" | "بالانتظار" | "مكتمل"; startsAt?: string };
type ClinicDataReply = { error?: string; patients?: Patient[]; appointments?: Appointment[]; clinic?: { name: string; trialEndsAt?: string|null };branch?:{id:string;name:string;branches:{id:string;name:string}[]}; user?: { isSuperAdmin?: boolean; role?: string }; counts?: { patients?: number }; patient?: Patient; appointment?: Appointment };
type SearchResult={id:string;name:string;kind:'patient'|'doctor'|'employee';section:Section};

const dictionaries: Record<Language, Record<string, string>> = {
  ar: { daily_work:"العمل اليومي",care:"الرعاية الطبية",team:"الفريق والمرضى",money:"المالية",resources:"الموارد",insights:"المتابعة والتقارير",dashboard: "لوحة التحكم", patients: "المرضى", appointments: "المواعيد", doctors: "الأطباء والموظفون", billing: "الفواتير والمحاسبة", reports: "التقارير", inventory: "المخزون والصيدلية", lab: "المختبر والأشعة", settings: "الإعدادات", welcome: "صباح الخير، د. نبيل", sub: "إليك ملخص نشاط العيادة لهذا اليوم.", today: "الثلاثاء، 29 سبتمبر 2026", addAppt: "موعد جديد", addPatient: "إضافة مريض", todayAppts: "مواعيد اليوم", allAppts: "عرض كل المواعيد", arrivals: "حالة المواعيد", revenue: "إيرادات اليوم", patientsCount: "إجمالي المرضى", occupancy: "إشغال العيادة", waiting: "في الانتظار", completed: "مكتمل", next: "قادم", search: "ابحث عن مريض أو طبيب أو موظف...", doctor: "الطبيب", service: "الخدمة", patient: "المريض", time: "الوقت", status: "الحالة", activity: "نشاط العيادة", week: "هذا الأسبوع", viewAll: "عرض الكل", quick: "اختصارات سريعة", newInvoice: "إنشاء فاتورة", labResults: "نتائج المختبر", lowStock: "مخزون منخفض", sample: "بيانات تجريبية", sampleNote: "استخدم هذه الواجهة للتجربة فقط. لا تدخل بيانات مرضى حقيقية.", patientsTitle: "إدارة المرضى", patientsSub: "الملفات الطبية والزيارات الأخيرة", doctorsTitle: "فريق العيادة", doctorsSub: "الأطباء والدوام اليومي", billingTitle: "الفواتير والمدفوعات", billingSub: "ملخص مالي للعيادة بالشيقل الإسرائيلي", reportsTitle: "التقارير والإحصائيات", reportsSub: "مؤشرات الأداء خلال الفترة الحالية", inventoryTitle: "المخزون والصيدلية", inventorySub: "متابعة المستلزمات والأدوية", labTitle: "المختبر والأشعة", labSub: "طلبات الفحوصات ونتائجها", settingsTitle: "إعدادات النظام", settingsSub: "اللغة والعملة وتفضيلات العيادة", filter: "تصفية", export: "تصدير", save: "حفظ", cancel: "إلغاء", name: "الاسم الكامل", phone: "رقم الهاتف", patientId: "رقم الملف", addSuccess: "تمت الإضافة إلى بيانات العرض", newPatient: "مريض جديد", appointmentFor: "حجز موعد", date: "التاريخ", note: "ملاحظة", close: "إغلاق" },
  he: { daily_work:"עבודה יומית",care:"טיפול רפואי",team:"צוות ומטופלים",money:"כספים",resources:"משאבים",insights:"מעקב ודוחות",dashboard: "לוח בקרה", patients: "מטופלים", appointments: "תורים", doctors: "רופאים וצוות", billing: "חשבוניות וכספים", reports: "דוחות", inventory: "מלאי ובית מרקחת", lab: "מעבדה והדמיה", settings: "הגדרות", welcome: "בוקר טוב, ד״ר נביל", sub: "סיכום פעילות המרפאה להיום.", today: "יום שלישי, 29 בספטמבר 2026", addAppt: "תור חדש", addPatient: "הוספת מטופל", todayAppts: "תורי היום", allAppts: "כל התורים", arrivals: "סטטוס תורים", revenue: "הכנסות היום", patientsCount: "סך המטופלים", occupancy: "תפוסת המרפאה", waiting: "ממתין", completed: "הושלם", next: "הבא", search: "חיפוש מטופלים, רופאים או צוות...", doctor: "רופא", service: "שירות", patient: "מטופל", time: "שעה", status: "סטטוס", activity: "פעילות המרפאה", week: "השבוע", viewAll: "הצג הכל", quick: "קיצורי דרך", newInvoice: "חשבונית חדשה", labResults: "תוצאות מעבדה", lowStock: "מלאי נמוך", sample: "נתוני הדגמה", sampleNote: "ממשק זה מיועד להדגמה בלבד. אין להזין מידע רפואי אמיתי.", patientsTitle: "ניהול מטופלים", patientsSub: "תיקים רפואיים וביקורים אחרונים", doctorsTitle: "צוות המרפאה", doctorsSub: "רופאים ולוח עבודה יומי", billingTitle: "חשבוניות ותשלומים", billingSub: "סיכום פיננסי בשקלים חדשים", reportsTitle: "דוחות ונתונים", reportsSub: "מדדי ביצוע לתקופה הנוכחית", inventoryTitle: "מלאי ובית מרקחת", inventorySub: "מעקב אחר תרופות וציוד", labTitle: "מעבדה והדמיה", labSub: "הזמנות בדיקה ותוצאות", settingsTitle: "הגדרות מערכת", settingsSub: "שפה, מטבע והעדפות המרפאה", filter: "סינון", export: "ייצוא", save: "שמירה", cancel: "ביטול", name: "שם מלא", phone: "מספר טלפון", patientId: "מספר תיק", addSuccess: "נוסף לנתוני ההדגמה", newPatient: "מטופל חדש", appointmentFor: "קביעת תור", date: "תאריך", note: "הערה", close: "סגירה" },
  en: { daily_work:"Daily work",care:"Clinical care",team:"Team & patients",money:"Finance",resources:"Resources",insights:"Insights & reports",dashboard: "Dashboard", patients: "Patients", appointments: "Appointments", doctors: "Doctors & staff", billing: "Billing", reports: "Reports", inventory: "Inventory & pharmacy", lab: "Lab & imaging", settings: "Settings", welcome: "Good morning, Dr. Nabil", sub: "Here is your clinic activity for today.", today: "Tuesday, September 29, 2026", addAppt: "New appointment", addPatient: "Add patient", todayAppts: "Today’s appointments", allAppts: "View all appointments", arrivals: "Appointment status", revenue: "Today’s revenue", patientsCount: "Total patients", occupancy: "Clinic occupancy", waiting: "Waiting", completed: "Completed", next: "Upcoming", search: "Search patients, doctors or staff...", doctor: "Doctor", service: "Service", patient: "Patient", time: "Time", status: "Status", activity: "Clinic activity", week: "This week", viewAll: "View all", quick: "Quick actions", newInvoice: "Create invoice", labResults: "Lab results", lowStock: "Low stock", sample: "Demo data", sampleNote: "Preview interface only. Do not enter real patient information.", patientsTitle: "Patient management", patientsSub: "Medical files and recent visits", doctorsTitle: "Clinic team", doctorsSub: "Doctors and daily schedules", billingTitle: "Invoices & payments", billingSub: "Clinic finances in Israeli shekels", reportsTitle: "Reports & analytics", reportsSub: "Performance indicators for this period", inventoryTitle: "Inventory & pharmacy", inventorySub: "Track supplies and medicines", labTitle: "Lab & imaging", labSub: "Test requests and results", settingsTitle: "System settings", settingsSub: "Language, currency and clinic preferences", filter: "Filter", export: "Export", save: "Save", cancel: "Cancel", name: "Full name", phone: "Phone number", patientId: "File number", addSuccess: "Added to demo data", newPatient: "New patient", appointmentFor: "Book appointment", date: "Date", note: "Note", close: "Close" },
};
const extra: Record<Language, Record<string, string>> = {
  ar: { licenses: "الاشتراكات والتراخيص", licenseTitle: "إدارة الاشتراكات والتراخيص", licenseSub: "سجّل الدفعة ثم أصدر رمز تفعيل فريدًا للعيادة.", appTag: "بيانات محفوظة ومشفّرة", appNote: "تُفصل بيانات كل عيادة عن الأخرى. لا تشارك رمز الترخيص إلا مع جهة الاتصال المسجلة.", addSuccess: "تم حفظ السجل في قاعدة البيانات", loading: "جارٍ الاتصال بقاعدة البيانات…", loadError: "تعذر تحميل بيانات العيادة", noAppointments: "لا توجد مواعيد محفوظة بعد", noPatients: "لا يوجد مرضى مسجلون بعد", licenseAdmin: "إدارة البرنامج", clinicName: "اسم العيادة", email: "البريد الإلكتروني", plan: "الباقة", term: "مدة الاشتراك", monthly: "شهري", annual: "سنوي", amount: "المبلغ بالشيقل", paymentRef: "مرجع الدفعة / الإيصال", createSub: "تسجيل اشتراك", confirmPaid: "تأكيد استلام الدفعة وإصدار الترخيص", pending: "بانتظار الدفع", paid: "مدفوع", activated: "مفعّل", issued: "صادر", enterPaid: "سجّل مبلغًا لا يقل عن قيمة الاشتراك ومرجع الدفعة. سيُعرض رمز الترخيص مرة واحدة فقط.", oneTimeKey: "رمز الترخيص — انسخه الآن", copy: "نسخ الرمز", gateway: "رابط بوابة SMS (HTTPS)", sender: "اسم المرسل", token: "مفتاح API", testPhone: "رقم هاتف الاختبار", testSms: "إرسال رسالة اختبار", saveSettings: "حفظ إعداد SMS", smsNote: "يلزم بوابة SMS تقبل POST بصيغة JSON: to, from, text مع Bearer token. لا ترسل رسالة حتى تضغط زر الاختبار.", configured: "مُعدّ", notConfigured: "غير مُعدّ", activate: "تفعيل الترخيص", activationKey: "رمز التفعيل", activateClinic: "تفعيل العيادة", activationNote: "أدخل الرمز الذي أصدرته إدارة عيادتي بعد تأكيد الاشتراك." },
  he: { licenses: "מנויים ורישיונות", licenseTitle: "ניהול מנויים ורישיונות", licenseSub: "רשום תשלום ואז צור קוד הפעלה ייחודי למרפאה.", appTag: "נתונים מוצפנים ונשמרים", appNote: "נתוני כל מרפאה מופרדים. יש למסור את קוד הרישיון רק לאיש הקשר הרשום.", addSuccess: "הרשומה נשמרה במסד הנתונים", loading: "מתחבר למסד הנתונים…", loadError: "לא ניתן לטעון את נתוני המרפאה", noAppointments: "אין תורים שמורים עדיין", noPatients: "אין מטופלים רשומים עדיין", licenseAdmin: "ניהול התוכנית", clinicName: "שם המרפאה", email: "דוא״ל", plan: "תוכנית", term: "תקופת מנוי", monthly: "חודשי", annual: "שנתי", amount: "סכום בשקלים", paymentRef: "אסמכתת תשלום", createSub: "רישום מנוי", confirmPaid: "אישור תשלום והנפקת רישיון", pending: "ממתין לתשלום", paid: "שולם", activated: "מופעל", issued: "הונפק", enterPaid: "הזן סכום ששולם ואסמכתה. קוד הרישיון יוצג פעם אחת בלבד.", oneTimeKey: "קוד רישיון — העתק כעת", copy: "העתקת קוד", gateway: "כתובת שער SMS (HTTPS)", sender: "מזהה שולח", token: "מפתח API", testPhone: "טלפון לבדיקה", testSms: "שליחת הודעת בדיקה", saveSettings: "שמירת הגדרות SMS", smsNote: "נדרש שער SMS התומך ב-POST JSON: to, from, text עם Bearer token. הודעה תישלח רק לאחר לחיצה על כפתור הבדיקה.", configured: "מוגדר", notConfigured: "לא מוגדר", activate: "הפעלת רישיון", activationKey: "קוד הפעלה", activateClinic: "הפעלת מרפאה", activationNote: "הזן את הקוד שהונפק לאחר אישור המנוי." },
  en: { licenses: "Subscriptions & licenses", licenseTitle: "Subscription and license admin", licenseSub: "Record the payment, then issue a unique activation code to the clinic.", appTag: "Encrypted, persistent records", appNote: "Each clinic’s data is isolated. Share a license code only with its registered contact.", addSuccess: "Saved to the clinic database", loading: "Connecting to the clinic database…", loadError: "Could not load clinic data", noAppointments: "No appointments saved yet", noPatients: "No patients registered yet", licenseAdmin: "Program administration", clinicName: "Clinic name", email: "Email address", plan: "Plan", term: "Subscription term", monthly: "Monthly", annual: "Annual", amount: "Amount in ILS", paymentRef: "Payment reference / receipt", createSub: "Record subscription", confirmPaid: "Confirm payment and issue license", pending: "Pending payment", paid: "Paid", activated: "Active", issued: "Issued", enterPaid: "Enter an amount at least equal to the plan and a payment reference. The license code is shown once.", oneTimeKey: "License code — copy it now", copy: "Copy code", gateway: "SMS gateway URL (HTTPS)", sender: "Sender ID", token: "API token", testPhone: "Test phone number", testSms: "Send test message", saveSettings: "Save SMS settings", smsNote: "Requires an SMS gateway accepting POST JSON {to, from, text} with a Bearer token. No message is sent until you press Test.", configured: "Configured", notConfigured: "Not configured", activate: "Activate license", activationKey: "Activation code", activateClinic: "Activate clinic", activationNote: "Enter the code issued by the program administrator after subscription payment." },
};
const tr = (lang: Language, key: string) => dictionaries[lang][key] ?? extra[lang][key] ?? opsText(lang,key);
const navGroups: { id: string; items: { id: Section; icon: typeof LayoutDashboard }[] }[] = [
 {id:"daily_work",items:[{id:"dashboard",icon:LayoutDashboard},{id:"appointments",icon:CalendarDays},{id:"queue",icon:Clock3},{id:"booking_requests",icon:CalendarDays},{id:"waitlist",icon:Clock3}]},
 {id:"care",items:[{id:"patients",icon:Users},{id:"specialty",icon:Stethoscope},{id:"visits",icon:HeartPulse},{id:"prescriptions",icon:FileText},{id:"lab",icon:FlaskConical},{id:"files",icon:FileText},{id:"consents",icon:ShieldCheck}]},
 {id:"team",items:[{id:"doctors",icon:Stethoscope},{id:"attendance",icon:Clock3},{id:"branches",icon:HeartPulse},{id:"users",icon:Users},{id:"portal_access",icon:ShieldCheck},{id:"feedback",icon:Users},{id:"complaints",icon:Bell}]},
 {id:"money",items:[{id:"billing",icon:WalletCards},{id:"insurance",icon:ShieldCheck},{id:"packages",icon:Package},{id:"commissions",icon:WalletCards},{id:"payroll",icon:WalletCards},{id:"expenses",icon:WalletCards}]},
 {id:"resources",items:[{id:"inventory",icon:Package},{id:"suppliers",icon:Package},{id:"services",icon:Activity}]},
 {id:"insights",items:[{id:"reports",icon:Activity},{id:"audit",icon:FileText},{id:"licenses",icon:KeyRound}]},
];
const titles: Partial<Record<Section, string>> = { dashboard: "dashboard", patients: "patientsTitle", appointments: "appointments", doctors: "doctorsTitle", billing: "billingTitle", reports: "reportsTitle", inventory: "inventoryTitle", lab: "labTitle", licenses: "licenseTitle", settings: "settingsTitle" };
const subtitles: Partial<Record<Section, string>> = { dashboard: "sub", patients: "patientsSub", appointments: "todayAppts", doctors: "doctorsSub", billing: "billingSub", reports: "reportsSub", inventory: "inventorySub", lab: "labSub", licenses: "licenseSub", settings: "settingsSub" };

export default function Home(){
 const [lang,setLang]=useState<Language>('ar'),[section,setSection]=useState<Section>('dashboard');
 const [dark,setDark]=useState(false),[mobileNav,setMobileNav]=useState(false),[query,setQuery]=useState(''),[toast,setToast]=useState('');
 const [openNavGroups,setOpenNavGroups]=useState<string[]>(['daily_work']);
 const [session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false),[recoveryMode,setRecoveryMode]=useState(false);
 const [authError,setAuthError]=useState(false);
 const [backendReady,setBackendReady]=useState(false),[backendError,setBackendError]=useState(''),[activationRequired,setActivationRequired]=useState(false);
 const [isSuperAdmin,setIsSuperAdmin]=useState(false),[role,setRole]=useState(''),[clinicName,setClinicName]=useState('');
 const [branches,setBranches]=useState<{id:string;name:string}[]>([]),[activeBranch,setActiveBranch]=useState('');
 const [searchResults,setSearchResults]=useState<SearchResult[]>([]),[searchDone,setSearchDone]=useState(false);
 const searchRef=useRef<HTMLInputElement>(null);
 const [trialEndsAt,setTrialEndsAt]=useState<string|null>(null),[activationKey,setActivationKey]=useState(''),[activationClinicName,setActivationClinicName]=useState(''),[createSignal,setCreateSignal]=useState(0);
 const t=dictionaries[lang],rtl=lang!=='en';
 const notify=useCallback((message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),4000);},[]);
 useEffect(()=>{
  queueMicrotask(()=>{const stored=localStorage.getItem('clinic-preferences-v1');if(stored){try{const p=JSON.parse(stored);if(['ar','he','en'].includes(p.lang))setLang(p.lang);setDark(p.dark===true);}catch{}}
  if(new URLSearchParams(window.location.search).get('verification')==='return')setSection('settings');
  });
  void supabase.auth.getSession().then(({data,error})=>{setSession(data.session);setAuthError(Boolean(error)||Boolean(authReturn?.hasError));if(data.session&&authReturn?.recovery)setRecoveryMode(true);if(authReturn?.hasError)window.history.replaceState(null,'',authReturn.cleanPath);}).catch(()=>{setSession(null);setAuthError(true);}).finally(()=>setAuthReady(true));
  const {data:{subscription}}=supabase.auth.onAuthStateChange((event,next)=>{setSession(next);if(event==='PASSWORD_RECOVERY')setRecoveryMode(true);setAuthReady(true);});return()=>subscription.unsubscribe();
 },[]);
 useEffect(()=>{if(authReady)localStorage.setItem('clinic-preferences-v1',JSON.stringify({lang,dark}));},[lang,dark,authReady]);
 useEffect(()=>{if(!session?.access_token||query.trim().length<2){setSearchResults([]);setSearchDone(false);return;}let active=true;setSearchDone(false);const timer=window.setTimeout(()=>{void authFetch('/api/search?q='+encodeURIComponent(query.trim())).then(async r=>{const d=await r.json() as {results?:SearchResult[]};if(active&&r.ok)setSearchResults(d.results??[]);}).catch(()=>{if(active)setSearchResults([]);}).finally(()=>{if(active)setSearchDone(true);});},240);return()=>{active=false;window.clearTimeout(timer);};},[query,session?.access_token]);
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();searchRef.current?.focus();}if(event.key==='Escape'){if(query){setQuery('');setSearchResults([]);}else if(mobileNav)setMobileNav(false);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[query,mobileNav]);
 useEffect(()=>{if(!authReady||!session?.access_token)return;let active=true;queueMicrotask(()=>{if(active){setBackendReady(false);setBackendError('');}});authFetch('/api/clinic-data').then(async r=>{if(r.status===403&&localStorage.getItem('clinic-active-branch')){localStorage.removeItem('clinic-active-branch');return authFetch('/api/clinic-data');}return r;}).then(async r=>{const d=await r.json() as ClinicDataReply;if(!active)return;if(r.status===403||r.status===402){setActivationRequired(true);return;}if(!r.ok)throw new Error(d.error||tr(lang,'loadError'));setActivationRequired(false);setClinicName(d.clinic?.name??'');setIsSuperAdmin(Boolean(d.user?.isSuperAdmin));setRole(d.user?.role??'');setTrialEndsAt(d.clinic?.trialEndsAt??null);setBranches(d.branch?.branches??[]);setActiveBranch(d.branch?.id??'');if(d.branch?.id)localStorage.setItem('clinic-active-branch',d.branch.id);}).catch(e=>{if(active)setBackendError(e instanceof Error?e.message:tr(lang,'loadError'));}).finally(()=>{if(active)setBackendReady(true);});return()=>{active=false;};},[authReady,session?.access_token,lang]);
 const activateClinic=async()=>{try{const r=await authFetch('/api/license/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({licenseKey:activationKey,clinicName:activationClinicName})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);window.location.reload();}catch(e){notify(e instanceof Error?e.message:tr(lang,'loadError'));}};
 function navigate(id:Section){setSection(id);setMobileNav(false);setQuery('');setSearchResults([]);setCreateSignal(0);const group=navGroups.find(g=>g.items.some(item=>item.id===id));if(group)setOpenNavGroups(current=>current.includes(group.id)?current:[...current,group.id]);window.scrollTo({top:0,behavior:'smooth'});}
 if(!authReady)return <div className="site-loading" aria-label="Loading"/>;
 if(recoveryMode)return <AuthScreen lang={lang} onLanguageChange={setLang} initialMode="update" onPasswordUpdated={async()=>{const {error}=await supabase.auth.signOut({scope:'local'});if(error)throw error;setRecoveryMode(false);}}/>;
 if(!session)return <MarketingSite authError={authError} lang={lang} onLanguageChange={setLang}/>;
 if(backendReady&&isSuperAdmin&&!backendError)return <><ProgramDashboard lang={lang} setLang={setLang} dark={dark} setDark={setDark} email={session.user.email??''} licenses={<LicenseManager lang={lang} notify={notify}/>}/>{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}</>;
 return <main dir={rtl?'rtl':'ltr'} className={`clinic-shell ${dark?'theme-dark':''}`}>
  <aside className={`sidebar ${mobileNav?'sidebar-open':''}`}>
   <div className="brand"><div className="brand-symbol"><HeartPulse size={23}/></div><div><strong>عيادتي</strong><small>CLINIC MANAGEMENT</small></div><button className="mobile-close icon-btn" onClick={()=>setMobileNav(false)} aria-label={t.close}><X size={20}/></button></div>
   <div className="clinic-select"><div className="clinic-dot">{clinicName.slice(0,1)||'+'}</div><div className="clinic-label"><b>{clinicName||tr(lang,'clinicName')}</b><small>₪ ILS · Palestine</small></div></div>
   <nav className="main-nav" aria-label={lang==='ar'?'القائمة الرئيسية':lang==='he'?'ניווט ראשי':'Main navigation'}>{navGroups.map(group=>{const items=group.items.filter(({id})=>id==='licenses'?isSuperAdmin:canAccess(role,id));const open=openNavGroups.includes(group.id);return items.length?<section className="nav-group" key={group.id}><button className="nav-group-toggle" aria-expanded={open} aria-controls={`nav-items-${group.id}`} onClick={()=>setOpenNavGroups(current=>open?current.filter(id=>id!==group.id):[...current,group.id])}><span>{tr(lang,group.id)}</span><ChevronDown size={16}/></button>{open&&<div id={`nav-items-${group.id}`} className="nav-group-items">{items.map(({id,icon:Icon})=><button key={id} aria-current={section===id?'page':undefined} className={`nav-item ${section===id?'active':''}`} onClick={()=>navigate(id)}><Icon size={19}/><span>{tr(lang,id)}</span></button>)}</div>}</section>:null})}</nav>
   <button className={`nav-item ${section==='settings'?'active':''}`} onClick={()=>navigate('settings')}><Settings2 size={19}/><span>{t.settings}</span></button>
   <div className="sidebar-bottom"><div className="profile-row"><div className="avatar avatar-me"><UserRound size={18}/></div><div className="profile-info"><b>{session.user.email}</b><small>{opsText(lang,role)}</small></div></div><button className="button button-outline" onClick={()=>void supabase.auth.signOut()}>{lang==='ar'?'تسجيل الخروج':lang==='he'?'התנתקות':'Sign out'}</button></div>
  </aside>
  {mobileNav&&<button className="nav-scrim" onClick={()=>setMobileNav(false)} aria-label={t.close}/>}
   <section className="workspace"><header className="topbar"><div className="topbar-start"><button className="mobile-menu icon-btn" onClick={()=>setMobileNav(true)} aria-label={lang==='ar'?'فتح القائمة':lang==='he'?'פתיחת התפריט':'Open menu'}><Menu size={21}/></button><div className="breadcrumbs"><span>{clinicName}</span><ChevronLeft size={14}/><b>{tr(lang,section)}</b></div></div><div className="topbar-end">{branches.length>1&&<select aria-label={lang==='ar'?'الفرع':lang==='he'?'סניף':'Branch'} value={activeBranch} onChange={e=>{localStorage.setItem('clinic-active-branch',e.target.value);setActiveBranch(e.target.value);}}>{branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select>}<div className="global-search-wrap"><label className="searchbox"><Search size={17}/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>query.length>1&&setSearchResults(r=>r)} aria-label={t.search} aria-expanded={query.trim().length>1} aria-controls="global-search-results" placeholder={t.search}/><kbd className="search-shortcut">Ctrl K</kbd></label>{query.trim().length>1&&<div className="global-search-results" id="global-search-results" role="listbox" aria-label={t.search}>{searchResults.map(result=><button role="option" aria-selected="false" key={result.section+result.id} onClick={()=>{setSection(result.section);setSearchResults([]);setSearchDone(false);setMobileNav(false);window.scrollTo({top:0,behavior:'smooth'});}}><span>{result.name}</span><small>{result.kind==='patient'?tr(lang,'patients'):result.kind==='doctor'?tr(lang,'doctor'):tr(lang,'doctors')}</small></button>)}{searchDone&&searchResults.length===0&&<p className="search-empty">{lang==='ar'?'لا توجد نتائج مطابقة':lang==='he'?'לא נמצאו תוצאות':'No matching results'}</p>}</div>}</div><button className="icon-btn lang-button" onClick={()=>setLang(lang==='ar'?'he':lang==='he'?'en':'ar')} title={lang==='ar'?'تغيير اللغة':lang==='he'?'שינוי שפה':'Change language'}><Languages size={18}/><span>{lang.toUpperCase()}</span></button><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label={lang==='ar'?(dark?'المظهر الفاتح':'المظهر الداكن'):lang==='he'?'ערכת נושא':'Theme'}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>{canAccess(role,'inventory')&&<button className="icon-btn" onClick={()=>navigate('notifications')} aria-label={opsText(lang,'notifications')}><Bell size={18}/></button>}</div></header>
   <div className="content-area"><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/>{new Intl.DateTimeFormat(lang==='ar'?'ar-PS':lang==='he'?'he-IL':'en-IL',{dateStyle:'full',timeZone:'Asia/Hebron'}).format(new Date())}</div><h1>{tr(lang,titles[section]??section)}</h1><p>{subtitles[section]?tr(lang,subtitles[section]!):tr(lang,'appTag')}</p></div>{backendReady&&!activationRequired&&!backendError&&<div className="heading-actions">{canAccess(role,'patients',true)&&<button className="button button-outline" onClick={()=>{navigate('patients');setCreateSignal(n=>n+1);}}><Plus size={17}/>{t.addPatient}</button>}{canAccess(role,'appointments',true)&&<button className="button button-primary" onClick={()=>{navigate('appointments');setCreateSignal(n=>n+1);}}><Plus size={18}/>{t.addAppt}</button>}</div>}</div>
    <div className="demo-banner"><ShieldCheck size={17}/><b>{tr(lang,'appTag')}</b><span>{tr(lang,'appNote')}</span></div>
    {trialEndsAt&&!activationRequired&&<p className="subscriber-notice">{lang==='ar'?'حساب تجريبي مجاني — ينتهي في':lang==='he'?'ניסיון חינם עד':'Free trial ends on'} {new Intl.DateTimeFormat(lang,{dateStyle:'long',timeZone:'Asia/Hebron'}).format(new Date(trialEndsAt))}</p>}
    {!backendReady&&<div className="panel empty-state">{tr(lang,'loading')}</div>}{backendError&&<div className="error-banner" role="alert">{backendError}<button onClick={()=>window.location.reload()}>{opsText(lang,'retry')}</button></div>}
    {activationRequired&&<><div className="panel activation-panel"><h2>{tr(lang,'activate')}</h2><p>{tr(lang,'activationNote')}</p><div className="activation-fields"><label className="form-label">{tr(lang,'clinicName')}<input value={activationClinicName} onChange={e=>setActivationClinicName(e.target.value)}/></label><label className="form-label">{tr(lang,'activationKey')}<input dir="ltr" value={activationKey} onChange={e=>setActivationKey(e.target.value.toUpperCase())}/></label><button className="button button-primary" onClick={activateClinic}>{tr(lang,'activateClinic')}</button></div></div><TrialRequestPanel lang={lang}/><SubscriptionCheckoutPanel lang={lang}/></>}
    {backendReady&&!backendError&&!activationRequired&&section!=='settings'&&section!=='licenses'&&section!=='specialty'&&!['queue','booking_requests','portal_access'].includes(section)&&<ClinicWorkspace key={`${section}-${activeBranch}`} section={section} lang={lang} role={role} query={query} createSignal={createSignal}/>}
    {backendReady&&!backendError&&!activationRequired&&section==='queue'&&<QueuePanel key={activeBranch} lang={lang}/>}
    {backendReady&&!backendError&&!activationRequired&&section==='booking_requests'&&<BookingRequestsPanel key={activeBranch} lang={lang}/>}
    {backendReady&&!backendError&&!activationRequired&&section==='portal_access'&&<PortalAccessPanel key={activeBranch} lang={lang}/>}
    {backendReady&&!backendError&&!activationRequired&&section==='specialty'&&<SpecialtyWorkspace key={activeBranch} lang={lang} role={role}/>}
    {!activationRequired&&section==='licenses'&&isSuperAdmin&&<><TrialAdminPanel lang={lang}/><LicenseManager lang={lang} notify={notify}/></>}
    {section==='settings'&&<MfaPanel lang={lang}/>}
    {section==='settings'&&<VerificationPanel lang={lang} isSuperAdmin={isSuperAdmin}/>}{section==='settings'&&isSuperAdmin&&<EmailSettingsPanel lang={lang}/>}{!activationRequired&&section==='settings'&&role==='clinic_admin'&&<><ClinicSettingsPanel lang={lang} role={role}/><IntegrationsPanel lang={lang}/><SmsSettingsPanel lang={lang} notify={notify}/><ClinicWebsiteSettings lang={lang}/></>}
    {section==='settings'&&<div className="panel ops-chart"><h2>{t.settings}</h2><div className="ops-fields"><label className="form-label">{lang==='ar'?'اللغة':lang==='he'?'שפה':'Language'}<select value={lang} onChange={e=>setLang(e.target.value as Language)}><option value="ar">العربية</option><option value="he">עברית</option><option value="en">English</option></select></label><label className="form-label">{lang==='ar'?'المظهر':lang==='he'?'תצוגה':'Appearance'}<select value={dark?'dark':'light'} onChange={e=>setDark(e.target.value==='dark')}><option value="light">{lang==='ar'?'فاتح':lang==='he'?'בהיר':'Light'}</option><option value="dark">{lang==='ar'?'داكن':lang==='he'?'כהה':'Dark'}</option></select></label><p>₪ ILS · Asia/Hebron</p></div></div>}
    <footer className="page-footer"><span>عيادتي © {new Date().getFullYear()}</span><span>{tr(lang,'appTag')}</span></footer>
   </div>
  </section>{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 </main>;
}

type SubscriptionRow={id:string;clinic_name:string;contact_email:string;plan:string;term:string;amount_ils:number;payment_status:string;payment_reference:string|null;license_status:string|null;key_hint:string|null;expires_at:string|null};
type SubscriptionListReply={error?:string;subscriptions?:SubscriptionRow[]};
type ApiMessageReply={error?:string;message?:string;configured?:boolean;gatewayUrl?:string;senderId?:string};
type IssuedLicenseReply={error?:string;license?:{key:string}};
function LicenseManager({lang,notify}:{lang:Language;notify:(s:string)=>void}){
  const [rows,setRows]=useState<SubscriptionRow[]>([]);const [clinicName,setClinicName]=useState("");const [email,setEmail]=useState("");const [plan,setPlan]=useState("professional");const [term,setTerm]=useState("monthly");const [customAmount,setCustomAmount]=useState("");const [selected,setSelected]=useState<SubscriptionRow|null>(null);const [paidAmount,setPaidAmount]=useState("");const [paymentRef,setPaymentRef]=useState("");const [newKey,setNewKey]=useState("");const [loading,setLoading]=useState(true);
  const plans:Record<string,string>={starter:"Starter",professional:"Professional",business:"Business",medical_center:"Medical Center",enterprise:"Enterprise"};
  const load=useCallback(()=>authFetch("/api/admin/subscriptions").then(async r=>{const d=await r.json() as SubscriptionListReply;if(!r.ok)throw new Error(d.error||tr(lang,"loadError"));setRows(d.subscriptions||[]);}).catch(e=>notify(e instanceof Error?e.message:tr(lang,"loadError"))).finally(()=>setLoading(false)),[lang,notify]);
  useEffect(()=>{void load();},[load]);
  const create=async()=>{try{const r=await authFetch("/api/admin/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clinicName,email,plan,term,language:lang,amountIls:customAmount?Number(customAmount):undefined})});const d=await r.json() as ApiMessageReply;if(!r.ok)throw new Error(d.error);setClinicName("");setEmail("");setCustomAmount("");notify(tr(lang,"pending"));await load();}catch(e){notify(e instanceof Error?e.message:tr(lang,"loadError"));}};
  const confirm=async()=>{if(!selected)return;try{const r=await authFetch("/api/admin/subscriptions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,paymentReference:paymentRef,paidAmount:Number(paidAmount)})});const d=await r.json() as IssuedLicenseReply;if(!r.ok)throw new Error(d.error);if(!d.license?.key)throw new Error(tr(lang,"loadError"));setNewKey(d.license.key);setSelected(null);setPaymentRef("");setPaidAmount("");await load();}catch(e){notify(e instanceof Error?e.message:tr(lang,"loadError"));}};
  const copy=async()=>{try{await navigator.clipboard.writeText(newKey);notify(tr(lang,"copy"));}catch{notify("انسخ الرمز يدويًا");}};
  return <><div className="license-intro panel"><div className="module-title"><div className="module-emblem"><KeyRound size={23}/></div><div><h2>{tr(lang,"licenseAdmin")}</h2><p>{tr(lang,"licenseSub")}</p></div></div><p className="license-rule">{tr(lang,"enterPaid")}</p></div><div className="panel license-create"><h2>{tr(lang,"createSub")}</h2><div className="license-fields"><label className="form-label">{tr(lang,"clinicName")}<input value={clinicName} onChange={e=>setClinicName(e.target.value)}/></label><label className="form-label">{tr(lang,"email")}<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="form-label">{tr(lang,"plan")}<select value={plan} onChange={e=>setPlan(e.target.value)}>{Object.entries(plans).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="form-label">{tr(lang,"term")}<select value={term} onChange={e=>setTerm(e.target.value)}><option value="monthly">{tr(lang,"monthly")}</option><option value="annual">{tr(lang,"annual")}</option></select></label>{plan==="enterprise"&&<label className="form-label">{tr(lang,"amount")}<input type="number" min="1" value={customAmount} onChange={e=>setCustomAmount(e.target.value)}/></label>}<button className="button button-primary license-create-btn" onClick={create}><Plus size={16}/>{tr(lang,"createSub")}</button></div></div><div className="panel license-list"><div className="panel-heading"><div><h2>{tr(lang,"licenses")}</h2><p>{rows.length} اشتراك مسجل</p></div><span className="admin-pill"><ShieldCheck size={14}/>{tr(lang,"licenseAdmin")}</span></div><div className="table-scroll"><table><thead><tr><th>{tr(lang,"clinicName")}</th><th>{tr(lang,"plan")}</th><th>{tr(lang,"amount")}</th><th>{tr(lang,"status")}</th><th>الترخيص</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><div><b>{row.clinic_name}</b><small className="table-sub">{row.contact_email}</small></div></td><td>{plans[row.plan]||row.plan} · {row.term==="annual"?tr(lang,"annual"):tr(lang,"monthly")}</td><td>{new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0}).format(row.amount_ils)}</td><td><span className={`license-state ${row.payment_status}`}>{row.payment_status==="paid"?tr(lang,"paid"):tr(lang,"pending")}</span></td><td>{row.license_status?<span className={`license-state ${row.license_status}`}>{row.license_status==="active"?tr(lang,"activated"):tr(lang,"issued")} ·••{row.key_hint}</span>:"—"}</td><td>{row.payment_status==="pending"&&<button className="button button-outline small-button" onClick={()=>{setSelected(row);setPaidAmount(String(row.amount_ils));}}>{tr(lang,"confirmPaid")}</button>}</td></tr>)}</tbody></table>{!loading&&rows.length===0&&<div className="empty-state">لا توجد اشتراكات مسجلة بعد</div>}</div></div>
    {newKey&&<div className="modal-backdrop"><div className="modal-card"><div className="modal-heading"><div><h2>{tr(lang,"oneTimeKey")}</h2><p>احفظ الرمز في مكان آمن، وراجع إعدادات البريد لمعرفة حالة إرسال إشعار الترخيص.</p></div><button className="icon-btn" onClick={()=>setNewKey("")}><X size={19}/></button></div><code className="license-code" dir="ltr">{newKey}</code><button className="button button-primary copy-button" onClick={copy}><Check size={16}/>{tr(lang,"copy")}</button></div></div>}
    {selected&&<div className="modal-backdrop"><div className="modal-card"><div className="modal-heading"><div><h2>{tr(lang,"confirmPaid")}</h2><p>{selected.clinic_name} · {currencySimple(selected.amount_ils)}</p></div><button className="icon-btn" onClick={()=>setSelected(null)}><X size={19}/></button></div><p className="license-rule">{tr(lang,"enterPaid")}</p><label className="form-label">{tr(lang,"amount")}<input type="number" value={paidAmount} onChange={e=>setPaidAmount(e.target.value)}/></label><label className="form-label">{tr(lang,"paymentRef")}<input value={paymentRef} onChange={e=>setPaymentRef(e.target.value)}/></label><div className="modal-actions"><button className="button button-outline" onClick={()=>setSelected(null)}>{tr(lang,"cancel")}</button><button className="button button-primary" onClick={confirm}>{tr(lang,"confirmPaid")}</button></div></div></div>}
  </>;
}
function currencySimple(amount:number){return new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0}).format(amount)}
function SmsSettingsPanel({lang,notify}:{lang:Language;notify:(s:string)=>void}){
  const [url,setUrl]=useState("");const [sender,setSender]=useState("");const [token,setToken]=useState("");const [phone,setPhone]=useState("");const [configured,setConfigured]=useState(false);const [saving,setSaving]=useState(false);
  useEffect(()=>{authFetch("/api/sms/settings").then(r=>r.json() as Promise<ApiMessageReply>).then(d=>{setUrl(d.gatewayUrl||"");setSender(d.senderId||"");setConfigured(Boolean(d.configured));}).catch(()=>notify(tr(lang,"loadError")));},[lang,notify]);
  const save=async()=>{setSaving(true);try{const r=await authFetch("/api/sms/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({gatewayUrl:url,senderId:sender,token})});const d=await r.json() as ApiMessageReply;if(!r.ok)throw new Error(d.error);setConfigured(true);setToken("");notify(tr(lang,"configured"));}catch(e){notify(e instanceof Error?e.message:tr(lang,"loadError"));}finally{setSaving(false);}};
  const test=async()=>{try{const r=await authFetch("/api/sms/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:phone})});const d=await r.json() as ApiMessageReply;if(!r.ok)throw new Error(d.error);notify(d.message||tr(lang,"testSms"));}catch(e){notify(e instanceof Error?e.message:tr(lang,"loadError"));}};
  return <div className="panel sms-panel"><div className="panel-heading"><div><h2>SMS</h2><p>تهيئة بوابة الرسائل النصية للعيادة</p></div><span className={`license-state ${configured?"active":"pending"}`}>{configured?tr(lang,"configured"):tr(lang,"notConfigured")}</span></div><p className="sms-note"><ShieldCheck size={16}/>{tr(lang,"smsNote")}</p><div className="sms-fields"><label className="form-label">{tr(lang,"gateway")}<input dir="ltr" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://sms-provider.example/api/messages"/></label><label className="form-label">{tr(lang,"sender")}<input dir="ltr" value={sender} onChange={e=>setSender(e.target.value)} placeholder="ClinicName"/></label><label className="form-label">{tr(lang,"token")}<input dir="ltr" type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder={configured?"••••••••••••••":"API token"}/></label></div><div className="sms-actions"><button className="button button-primary" onClick={save} disabled={saving}>{tr(lang,"saveSettings")}</button><label className="form-label test-phone">{tr(lang,"testPhone")}<input dir="ltr" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+97059…"/></label><button className="button button-outline" onClick={test} disabled={!configured||!phone}>{tr(lang,"testSms")}</button></div></div>;
}
