'use client';
import {useCallback,useEffect,useState,type ReactNode} from 'react';
import {Building2,LayoutDashboard,KeyRound,Clock3,Settings2,ShieldCheck,Menu,X,Languages,Moon,Sun,HeartPulse,FileText} from 'lucide-react';
import {label,specialties,type SpecialtyKey} from '../lib/ops-model';
import {MfaPanel} from './mfa-panel';
import {authFetch,supabase} from './auth-client';
import {TrialAdminPanel,EmailSettingsPanel} from './subscriber-panels';
import VerificationPanel from './verification-panel';
import OpenAISettingsPanel from './openai-settings-panel';
type Language='ar'|'he'|'en';
type Clinic={primary_specialty:SpecialtyKey;id:string;name:string;owner_email:string|null;license_status:string|null;expires_at:string|null;trial_ends_at:string|null;staff_count:number;branch_count:number};
type Overview={clinics:Clinic[];subscriptions:{total:number;receipts:number;pending:number};trials:{pending:number};audit:{id:string;action:string;resource_type:string;created_at:string;clinic_name:string|null}[]};
const labels={
 specialty:['التخصص الرئيسي','מומחיות ראשית','Primary specialty'],title:['إدارة البرنامج','ניהול המערכת','Program administration'],role:['مدير البرنامج بالكامل','מנהל מערכת ראשי','Program administrator'],
 overview:['لوحة إدارة البرنامج','סקירת המערכת','Program overview'],clinics:['العيادات المشتركة','מרפאות רשומות','Registered clinics'],licenses:['الاشتراكات والتراخيص','מנויים ורישיונות','Subscriptions & licenses'],trials:['طلبات التجربة المجانية','בקשות ניסיון חינם','Free trial requests'],settings:['إعدادات البرنامج والتكاملات','הגדרות וחיבורים','Program settings & integrations'],audit:['سجل نشاط البرنامج','יומן פעילות','Program activity'],
 intro:['متابعة العيادات والاشتراكات والتراخيص من مكان واحد.','ניהול מרפאות, מנויים ורישיונות במקום אחד.','Manage clinics, subscriptions and licenses in one place.'],
 receipts:['تحصيل الاشتراكات ₪','תקבולי מנויים ₪','Subscription receipts ₪'],pending:['اشتراكات بانتظار الدفع','מנויים ממתינים לתשלום','Subscriptions awaiting payment'],name:['العيادة','מרפאה','Clinic'],owner:['حساب مدير العيادة','חשבון מנהל מרפאה','Clinic administrator account'],status:['حالة الترخيص','סטטוס רישיון','License status'],branches:['الفروع الفعالة','סניפים פעילים','Active branches'],staff:['المستخدمون الفعالون','משתמשים פעילים','Active users'],expiry:['تاريخ الانتهاء','תאריך סיום','Expiry date'],active:['فعال','פעיל','Active'],expired:['منتهي','פג תוקף','Expired'],trial:['تجريبي','ניסיון','Trial'],unlicensed:['بلا ترخيص فعال','ללא רישיון פעיל','No active license'],empty:['لا توجد سجلات بعد','אין רשומות עדיין','No records yet'],loading:['جارٍ تحميل إدارة البرنامج…','טוען ניהול מערכת…','Loading program administration…'],retry:['إعادة المحاولة','נסה שוב','Retry'],signout:['تسجيل الخروج','התנתקות','Sign out'],search:['بحث باسم العيادة أو البريد','חיפוש שם מרפאה או דוא״ל','Search clinic name or email'],error:['تعذر تحميل إدارة البرنامج. أعد المحاولة.','לא ניתן לטעון את ניהול המערכת. נסה שוב.','Could not load program administration. Try again.'],action:['العملية','פעולה','Action'],date:['التاريخ','תאריך','Date']
} satisfies Record<string,[string,string,string]>;
type Tab='overview'|'clinics'|'licenses'|'trials'|'settings'|'audit';
export default function ProgramDashboard({lang,setLang,dark,setDark,email,licenses}:{lang:Language;setLang:(v:Language)=>void;dark:boolean;setDark:(v:boolean)=>void;email:string;licenses:ReactNode}){
 const t=(key:keyof typeof labels)=>labels[key][lang==='ar'?0:lang==='he'?1:2];
 const [tab,setTab]=useState<Tab>('overview'),[mobile,setMobile]=useState(false),[data,setData]=useState<Overview|null>(null),[error,setError]=useState(false),[query,setQuery]=useState('');
 const load=useCallback(async()=>{setError(false);try{const r=await authFetch('/api/admin/overview');if(!r.ok)throw new Error();setData(await r.json() as Overview);}catch{setError(true);}},[]);
 useEffect(()=>{void load();},[load]);
 const navigation:[Tab,typeof LayoutDashboard][]=[['overview',LayoutDashboard],['clinics',Building2],['licenses',KeyRound],['trials',Clock3],['settings',Settings2],['audit',FileText]];
 const open=(next:Tab)=>{setTab(next);setMobile(false);if(next==='overview'||next==='clinics'||next==='audit')void load();};
 const date=(v:string|null)=>v?new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeZone:'Asia/Hebron'}).format(new Date(v.includes('T')?v:v.replace(' ','T')+'Z')):'—';
 const status=(c:Clinic)=>c.license_status==='active'?(c.expires_at&&Date.parse(c.expires_at)>Date.now()?t('active'):t('expired')):c.trial_ends_at?(Date.parse(c.trial_ends_at)>Date.now()?t('trial'):t('expired')):t('unlicensed');
 return <main dir={lang==='en'?'ltr':'rtl'} className={`clinic-shell ${dark?'theme-dark':''}`}>
  <aside className={`sidebar ${mobile?'sidebar-open':''}`}><div className="brand"><div className="brand-symbol"><HeartPulse/></div><div><strong>عيادتي</strong><small>{t('title')}</small></div><button className="mobile-close icon-btn" onClick={()=>setMobile(false)} aria-label="Close"><X/></button></div><div className="clinic-select"><ShieldCheck/><div className="clinic-label"><b>{t('role')}</b><small>{t('title')}</small></div></div><nav className="main-nav">{navigation.map(([id,Icon])=><button key={id} className={`nav-item ${tab===id?'active':''}`} onClick={()=>open(id)}><Icon size={19}/><span>{t(id)}</span></button>)}</nav><div className="sidebar-bottom"><div className="profile-row"><ShieldCheck/><div className="profile-info"><b>{email}</b><small>{t('role')}</small></div></div><button className="button button-outline" onClick={()=>void supabase.auth.signOut()}>{t('signout')}</button></div></aside>
  {mobile&&<button className="nav-scrim" onClick={()=>setMobile(false)} aria-label="Close"/>}
  <section className="workspace"><header className="topbar"><div className="topbar-start"><button className="mobile-menu icon-btn" onClick={()=>setMobile(true)} aria-label="Menu"><Menu/></button><b>{t('title')}</b></div><div className="topbar-end"><button className="icon-btn lang-button" onClick={()=>setLang(lang==='ar'?'he':lang==='he'?'en':'ar')} aria-label="Language"><Languages/><span>{lang.toUpperCase()}</span></button><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label="Theme">{dark?<Sun/>:<Moon/>}</button></div></header>
   <div className="content-area"><div className="page-heading"><div><h1>{t(tab)}</h1><p>{t('intro')}</p></div></div>
    {tab==='licenses'&&licenses}{tab==='trials'&&<TrialAdminPanel lang={lang}/>}{tab==='settings'&&<><MfaPanel lang={lang}/><VerificationPanel lang={lang} isSuperAdmin/><EmailSettingsPanel lang={lang}/><OpenAISettingsPanel lang={lang}/></>}
    {['overview','clinics','audit'].includes(tab)&&<>{error?<div className="error-banner" role="alert">{t('error')}<button className="button button-outline" onClick={()=>void load()}>{t('retry')}</button></div>:!data?<div className="panel empty-state">{t('loading')}</div>:<>
     {tab==='overview'&&<div className="stats-grid ops-stats">{([['clinics',data.clinics.length],['licenses',data.subscriptions.total],['receipts',new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(data.subscriptions.receipts)],['pending',data.subscriptions.pending],['trials',data.trials.pending]] as [keyof typeof labels,string|number][]).map(([k,v])=><article className="stat-card" key={k}><span>{t(k)}</span><div className="stat-value">{v}</div></article>)}</div>}
     {(tab==='overview'||tab==='clinics')&&<div className="panel"><div className="panel-heading"><h2>{t('clinics')}</h2><input aria-label={t('search')} placeholder={t('search')} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-scroll"><table><thead><tr>{(['name','specialty','owner','status','branches','staff','expiry'] as const).map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.clinics.filter(c=>(c.name+' '+c.owner_email).toLowerCase().includes(query.toLowerCase())).map(c=><tr key={c.id}><td>{c.name}</td><td>{specialties[c.primary_specialty]?label(specialties[c.primary_specialty].title,lang):c.primary_specialty}</td><td>{c.owner_email??'—'}</td><td>{status(c)}</td><td>{c.branch_count}</td><td>{c.staff_count}</td><td>{date(c.expires_at??c.trial_ends_at)}</td></tr>)}</tbody></table>{!data.clinics.length&&<p className="empty-state">{t('empty')}</p>}</div></div>}
     {tab==='audit'&&<div className="panel table-scroll"><table><thead><tr><th>{t('action')}</th><th>{t('name')}</th><th>{t('date')}</th></tr></thead><tbody>{data.audit.map(a=><tr key={a.id}><td>{a.action}</td><td>{a.clinic_name??t('title')}</td><td>{date(a.created_at)}</td></tr>)}</tbody></table>{!data.audit.length&&<p className="empty-state">{t('empty')}</p>}</div>}
    </>}</>}
   </div>
  </section>
 </main>;
}
