'use client';
import {useEffect,useRef,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {authFetch,supabase} from './auth-client';
import {AuthScreen} from './auth-screen';
import {clinicDate} from '../lib/clinic-time';
import type {Language} from '../lib/ops-model';
export default function PublicBooking({slug}:{slug:string}){
 const [lang,setLang]=useState<Language>('ar'),[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[name,setName]=useState(''),[phone,setPhone]=useState(''),[service,setService]=useState(''),[preferredDate,setPreferredDate]=useState(clinicDate()),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);const requestKey=useRef<string|null>(null);
 const t=(ar:string,he:string,en:string)=>lang==='ar'?ar:lang==='he'?he:en;
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true);});const {data}=supabase.auth.onAuthStateChange((_,s)=>{setSession(s);setReady(true);});return()=>data.subscription.unsubscribe();},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{requestKey.current??=crypto.randomUUID();const r=await authFetch('/api/public/booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,name,phone,service,preferredDate,notes,requestKey:requestKey.current})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setDone(true);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 if(!ready)return <div className="site-loading"/>;
 if(!session)return <div dir={lang==='en'?'ltr':'rtl'}><div className="portal-intro"><a href={'/c/'+slug}>عيادتي</a><h1>{t('طلب موعد','בקשת תור','Request an appointment')}</h1><p>{t('سجّل الدخول أو أنشئ حسابًا للتحقق من البريد وإرسال الطلب للعيادة.','היכנסו או צרו חשבון לאימות דוא״ל ושליחת בקשה.','Sign in or create an account to verify your email and send a request to the clinic.')}</p></div><AuthScreen lang={lang} onLanguageChange={setLang} initialMode="signin"/></div>;
 return <main className="portal-page" dir={lang==='en'?'ltr':'rtl'}><div className="portal-content"><a href={'/c/'+slug}>{t('العودة للعيادة','חזרה למרפאה','Back to clinic')}</a><section className="panel booking-public"><h1>{t('طلب موعد','בקשת תור','Appointment request')}</h1><p>{t('سيتم إرسال الطلب إلى العيادة. الموعد غير مؤكد حتى تراجعه العيادة وتتواصل معك.','הבקשה תישלח למרפאה. התור אינו מאושר עד בדיקה ויצירת קשר.','Your request will be sent to the clinic. The appointment is not confirmed until they review it and contact you.')}</p><button className="button button-outline" onClick={()=>setLang(lang==='ar'?'he':lang==='he'?'en':'ar')}>{lang.toUpperCase()}</button>{done?<p className="subscriber-notice" role="status">{t('تم استلام الطلب. ستتواصل معك العيادة لتأكيد الوقت.','הבקשה התקבלה. המרפאה תיצור קשר לאישור מועד.','Request received. The clinic will contact you to confirm a time.')}</p>:<form onSubmit={submit}><fieldset disabled={busy}><div className="ops-fields"><label className="form-label">{t('الاسم','שם','Name')}<input required minLength={2} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-label">{t('الهاتف','טלפון','Phone')}<input required minLength={5} maxLength={40} type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="form-label">{t('الخدمة','שירות','Service')}<input required maxLength={120} value={service} onChange={e=>setService(e.target.value)}/></label><label className="form-label">{t('التاريخ المفضل','תאריך מועדף','Preferred date')}<input type="date" required min={clinicDate()} value={preferredDate} onChange={e=>setPreferredDate(e.target.value)}/></label><label className="form-label ops-wide">{t('ملاحظات تخص الموعد فقط','הערות לתור בלבד','Appointment notes only')}<textarea maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><p>{t('البريد المؤكد','דוא״ל מאומת','Verified email')}: {session.user.email}</p><button className="button button-primary" disabled={busy}>{busy?'…':t('إرسال الطلب','שליחת בקשה','Send request')}</button></fieldset></form>}{error&&<p className="error-banner" role="alert">{error}</p>}</section></div></main>;
}
