'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Plus,Save,Printer,RefreshCw,Stethoscope,ChevronLeft} from 'lucide-react';
import ClinicalAiPanel from './clinical-ai-panel';
import {authFetch} from './auth-client';
import {canAccess,label,specialties,specialtyKeys,toothStates,estimatedPregnancy,type SpecialtyKey,type Language,type Label} from '../lib/ops-model';
import {clinicDate} from '../lib/clinic-time';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
type Findings=Record<string,string|number>;
type Treatment={tooth:string;procedure:string;cost:number;status:'planned'|'completed'};
type Vaccine={name:string;date:string;dose:string;nextDate:string};
type RecordRow={id:string;version:number;patientId:string;name:string;specialty:SpecialtyKey;date:string;notes:string;plan:string;status:'draft'|'completed';findings?:Findings;teeth?:Record<string,string>;dentition?:'permanent'|'primary';treatments?:Treatment[];vaccines?:Vaccine[];nextVisit?:string;portalShared?:boolean};
type Draft=Omit<RecordRow,'id'|'version'>;
type Patient={id:string;name:string;birthDate?:string;allergies?:string};
type FileRow={id:string;name:string;mime:string};
const copy={patient:['المريض','מטופל','Patient'],date:['تاريخ الزيارة','תאריך ביקור','Visit date'],history:['سجل الزيارات','היסטוריית ביקורים','Visit history'],new:['زيارة تخصصية جديدة','ביקור מומחה חדש','New specialty visit'],save:['حفظ السجل','שמירת רשומה','Save record'],saved:['تم حفظ السجل','הרשומה נשמרה','Record saved'],failed:['تعذر تحميل أو حفظ السجل. أعد المحاولة.','לא ניתן לטעון או לשמור. נסו שוב.','Could not load or save the record. Retry.'],notes:['ملاحظات الفحص','הערות בדיקה','Examination notes'],plan:['خطة العلاج والمتابعة','תוכנית טיפול ומעקב','Treatment & follow-up plan'],next:['المراجعة القادمة','ביקור הבא','Next visit'],draft:['مسودة','טיוטה','Draft'],completed:['معتمد من الطبيب','אושר על ידי רופא','Clinician-approved'],title:['عنوان الزيارة','כותרת ביקור','Visit title'],measures:['الفحص والقياسات','בדיקה ומדדים','Examination & measurements'],tooth:['السن','שן','Tooth'],procedure:['الإجراء','הליך','Procedure'],cost:['التكلفة ₪','עלות ₪','Cost ₪'],empty:['اختر مريضًا لعرض سجله أو إضافة زيارة.','בחרו מטופל להצגת היסטוריה או ביקור חדש.','Select a patient to see history or add a visit.'],noVisits:['لا توجد زيارات لهذا التخصص بعد.','אין ביקורים למומחיות זו עדיין.','No visits for this specialty yet.'],edit:['فتح السجل','פתיחת רשומה','Open record'],cancel:['إغلاق المحرر','סגירת עורך','Close editor'],remove:['إزالة','הסרה','Remove'],share:['إتاحة السجل المعتمد للمريض في بوابته','שיתוף רשומה מאושרת בפורטל מטופל','Share the approved record in the patient portal'],growth:['القياسات عبر الزيارات','מדידות לאורך ביקורים','Measurements across visits'],review:['القياسات مدخلة من الفريق ولا تشكل تشخيصًا تلقائيًا. الطبيب يعتمد السجل وخطة العلاج.','המדדים הוזנו על ידי הצוות. אין אבחון אוטומטי. הרופא מאשר את הרשומה והתוכנית.','Team-entered measurements do not produce an automatic diagnosis. A clinician approves the record and treatment plan.']} satisfies Record<string,Label>;
const blank=(patientId:string,specialty:SpecialtyKey):Draft=>({patientId,specialty,name:'',date:clinicDate(),notes:'',plan:'',status:'draft',findings:{},teeth:{},dentition:'permanent',treatments:[],vaccines:[],nextVisit:'',portalShared:false});
const permanent=[[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28],[48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38]];
const primary=[[55,54,53,52,51,61,62,63,64,65],[85,84,83,82,81,71,72,73,74,75]];
function MedicalImage({id,title}:{id:string;title:string}){
 const [url,setUrl]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{const controller=new AbortController();let objectUrl='';setUrl('');setFailed(false);void authFetch('/api/medical-files?id='+encodeURIComponent(id),{signal:controller.signal}).then(async r=>{if(!r.ok||!r.headers.get('content-type')?.startsWith('image/'))throw new Error('Unavailable');const blob=await r.blob();if(controller.signal.aborted)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}).catch(()=>{if(!controller.signal.aborted)setFailed(true);});return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[id]);
 return <figure className="medical-photo"><figcaption>{title}</figcaption>{url?<img src={url} alt={title}/>:<p>{failed?'—':'…'}</p>}</figure>;
}
export default function SpecialtyWorkspace({lang,role}:{lang:Language;role:string}){
 const t=(key:keyof typeof copy)=>label(copy[key],lang),l=(v:Label)=>label(v,lang);
 const [enabled,setEnabled]=useState<SpecialtyKey[]>([...specialtyKeys]),[specialty,setSpecialty]=useState<SpecialtyKey>('general'),[patients,setPatients]=useState<Patient[]>([]),[patientId,setPatientId]=useState(''),[records,setRecords]=useState<RecordRow[]>([]),[files,setFiles]=useState<FileRow[]>([]);
 const initialized=useRef(false);
 const [draft,setDraft]=useState<Draft|null>(null),[editing,setEditing]=useState<RecordRow|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[toothState,setToothState]=useState('caries');
 const writable=canAccess(role,'specialty',true),approver=['clinic_admin','doctor'].includes(role),definition=specialties[specialty];
 const load=useCallback(async()=>{setLoading(true);setError('');try{
  const get=async<T,>(url:string)=>{const r=await authFetch(url);const d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error);return d;};
  const [recordData,patientData,config]=await Promise.all([get<{rows:RecordRow[]}>('/api/ops?module=specialty'),get<{rows:Patient[]}>('/api/ops?module=patients'),get<{settings:{enabledSpecialties:SpecialtyKey[];primarySpecialty:SpecialtyKey}}>('/api/clinic-settings')]);
  setRecords(recordData.rows);setPatients(patientData.rows);const keys=config.settings.enabledSpecialties.filter(k=>specialtyKeys.includes(k));setEnabled(keys);const firstLoad=!initialized.current;initialized.current=true;setSpecialty(old=>!firstLoad&&keys.includes(old)?old:config.settings.primarySpecialty);
 }catch(e){setError(e instanceof Error?e.message:label(copy.failed,lang));}finally{setLoading(false);}},[lang]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!patientId){setFiles([]);return;}let active=true;void authFetch('/api/medical-files?patientId='+patientId).then(async r=>{if(!r.ok)return;const d=await r.json() as {rows?:FileRow[]};if(active)setFiles(d.rows??[]);}).catch(()=>{});return()=>{active=false;};},[patientId]);
 const history=useMemo(()=>records.filter(r=>r.patientId===patientId&&r.specialty===specialty).sort((a,b)=>b.date.localeCompare(a.date)),[records,patientId,specialty]);
 const patient=patients.find(p=>p.id===patientId);
 const trend=useMemo(()=>[...history].reverse().map(r=>({date:r.date,...r.findings})),[history]);
 const metricKeys=specialty==='pediatrics'?['weight','height','headCircumference']:specialty==='physiotherapy'?['painScore','rangeOfMotion']:specialty==='ophthalmology'?['iopRight','iopLeft']:[];
 const patch=(key:keyof Draft,value:unknown)=>setDraft(old=>old?{...old,[key]:value}:old);
 const finding=(key:string,value:string,type:string)=>setDraft(old=>{if(!old)return old;const findings={...old.findings};if(value==='')delete findings[key];else findings[key]=type==='number'?Number(value):value;return {...old,findings};});
 const start=(row?:RecordRow)=>{setEditing(row??null);setError('');setNotice('');setDraft(row?{patientId:row.patientId,name:row.name,specialty:row.specialty,date:row.date,notes:row.notes,plan:row.plan??'',status:row.status,findings:row.findings??{},teeth:row.teeth??{},dentition:row.dentition??'permanent',treatments:row.treatments??[],vaccines:row.vaccines??[],nextVisit:row.nextVisit??'',portalShared:row.portalShared??false}:blank(patientId,specialty));};
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);setError('');try{const r=await authFetch('/api/ops',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module:'specialty',id:editing?.id,version:editing?.version,data:draft})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setDraft(null);setNotice(t('saved'));await load();}catch(e){setError(e instanceof Error?e.message:t('failed'));}finally{setBusy(false);}}
 const pregnancy=draft?.findings?.lmp?estimatedPregnancy(String(draft.findings.lmp),draft.date):null;
 return <div className="specialty-workspace"><div className="specialty-tabs no-print" role="tablist" aria-label={l(['التخصصات','מומחיות','Specialties'])}>{enabled.map(key=><button role="tab" aria-selected={key===specialty} key={key} disabled={busy} onClick={()=>{setSpecialty(key);setDraft(null);setNotice('');}}><Stethoscope size={16}/>{label(specialties[key].title,lang)}</button>)}</div>
 <div className="specialty-heading"><div><h2>{label(definition.title,lang)}</h2><p>{label(definition.description,lang)}</p></div><button className="button button-outline no-print" onClick={()=>void load()} disabled={loading||busy} aria-label={l(['تحديث','רענון','Refresh'])}><RefreshCw size={16}/></button></div>
 <div className="specialty-controls no-print"><label className="form-label">{t('patient')}<select value={patientId} disabled={busy} onChange={e=>{setPatientId(e.target.value);setDraft(null);}}><option value="">—</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{patientId&&writable&&<button className="button button-primary" disabled={busy||loading} onClick={()=>start()}><Plus size={16}/>{t('new')}</button>}</div>
 {error&&<div className="error-banner" role="alert">{error}</div>}{notice&&<p className="subscriber-notice" role="status">{notice}</p>}{loading&&<p role="status">{l(['جارٍ التحميل…','טוען…','Loading…'])}</p>}
 {patient?.allergies&&<p className="specialty-allergy">{l(['الحساسية المسجلة','אלרגיות מתועדות','Recorded allergies'])}: {patient.allergies}</p>}
 {!patientId?<div className="panel empty-state">{t('empty')}</div>:draft?<form className="panel specialty-editor" onSubmit={save}><div className="panel-heading"><h2>{editing?t('edit'):t('new')}</h2><button className="button button-outline no-print" type="button" disabled={busy} onClick={()=>setDraft(null)}>{t('cancel')}</button></div>
 <fieldset disabled={busy||!writable||!approver&&draft.status==='completed'}><div className="ops-fields"><label className="form-label">{t('title')}<input required maxLength={300} value={draft.name} onChange={e=>patch('name',e.target.value)}/></label><label className="form-label">{t('date')}<input type="date" required value={draft.date} onChange={e=>patch('date',e.target.value)}/></label></div><h3>{t('measures')}</h3><div className="ops-fields">{definition.measures.map(m=><label className={'form-label '+(m.type==='text'?'ops-wide':'')} key={m.key}>{label(m.title,lang)} {m.unit&&<small>({m.unit})</small>}{m.key==='beforeFileId'||m.key==='afterFileId'?<select value={draft.findings?.[m.key]??''} onChange={e=>finding(m.key,e.target.value,m.type)}><option value="">—</option>{files.filter(f=>f.mime.startsWith('image/')).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select>:m.type==='text'?<textarea maxLength={2000} value={draft.findings?.[m.key]??''} onChange={e=>finding(m.key,e.target.value,m.type)}/>:<input type={m.type} step="any" min={m.type==='number'?m.min:undefined} max={m.type==='number'?m.max:undefined} value={draft.findings?.[m.key]??''} onChange={e=>finding(m.key,e.target.value,m.type)}/>}</label>)}</div>
 {specialty==='dermatology'&&<div className="medical-photo-grid">{['beforeFileId','afterFileId'].map(key=>draft.findings?.[key]?<MedicalImage key={key} id={String(draft.findings[key])} title={label(definition.measures.find(m=>m.key===key)!.title,lang)}/>:null)}</div>}
 {specialty==='pediatrics'&&Number(draft.findings?.height)>0&&Number(draft.findings?.weight)>0&&<p className="specialty-calculation">BMI: {(Number(draft.findings?.weight)/(Number(draft.findings?.height)/100)**2).toFixed(2)} kg/m²</p>}
 {pregnancy&&<div className="specialty-calculation">{l(['عمر الحمل المحسوب من آخر دورة','גיל הריון מחושב','Gestational age from LMP'])}: {pregnancy.weeks} {l(['أسبوع','שבועות','weeks'])} + {pregnancy.days} {l(['يوم','ימים','days'])}<br/>{l(['موعد ولادة تقديري (280 يومًا)؛ يعتمد الطبيب الموعد النهائي','תאריך לידה משוער (280 ימים); הרופא מאשר תאריך','Estimated due date (280 days); clinician confirms the final date'])}: <b>{pregnancy.dueDate}</b></div>}
 {specialty==='dental'&&<section className="dental-section"><div className="specialty-controls"><h3>{l(['مخطط الأسنان FDI','תרשים שיניים FDI','FDI tooth chart'])}</h3><select aria-label={l(['نوع الأسنان','סוג משנן','Dentition'])} value={draft.dentition} onChange={e=>patch('dentition',e.target.value)}><option value="permanent">{l(['أسنان دائمة','שיניים קבועות','Permanent'])}</option><option value="primary">{l(['أسنان لبنية','שיני חלב','Primary'])}</option></select><select aria-label={l(['حالة السن','מצב שן','Tooth condition'])} value={toothState} onChange={e=>setToothState(e.target.value)}>{Object.entries(toothStates).map(([key,v])=><option value={key} key={key}>{label(v,lang)}</option>)}</select></div><p>{l(['اختر الحالة ثم اضغط على السن. العرض من منظور الطبيب: يمين المريض في يسار المخطط.','בחרו מצב ולחצו על שן. ימין המטופל בשמאל התרשים.','Choose a condition and select a tooth. Patient right appears on chart left.'])}</p><div className="tooth-chart" dir="ltr">{(draft.dentition==='primary'?primary:permanent).map((arch,index)=><div key={index}><span>{index===0?l(['الفك العلوي','לסת עליונה','Upper jaw']):l(['الفك السفلي','לסת תחתונה','Lower jaw'])}</span><div className={'tooth-arch '+(draft.dentition==='primary'?'primary-teeth':'')}>{arch.map(n=><button type="button" key={n} className={'tooth-cell tooth-'+(draft.teeth?.[String(n)]??'unrecorded')} aria-label={n+' '+(draft.teeth?.[String(n)]?label(toothStates[draft.teeth[String(n)]],lang):l(['غير مسجل','לא תועד','Unrecorded']))} onClick={()=>patch('teeth',{...draft.teeth,[String(n)]:toothState})}><b>{n}</b><small>{draft.teeth?.[String(n)]?label(toothStates[draft.teeth[String(n)]],lang):'—'}</small></button>)}</div></div>)}</div>
 <h3>{l(['خطة إجراءات الأسنان','תוכנית טיפולי שיניים','Dental treatment plan'])}</h3>{draft.treatments?.map((line,i)=><div className="specialty-plan-line" key={i}><label className="form-label">{t('tooth')}<input value={line.tooth} maxLength={2} onChange={e=>patch('treatments',draft.treatments?.map((v,j)=>j===i?{...v,tooth:e.target.value}:v))}/></label><label className="form-label">{t('procedure')}<input required value={line.procedure} maxLength={300} onChange={e=>patch('treatments',draft.treatments?.map((v,j)=>j===i?{...v,procedure:e.target.value}:v))}/></label><label className="form-label">{t('cost')}<input type="number" min={0} step="0.01" value={line.cost} onChange={e=>patch('treatments',draft.treatments?.map((v,j)=>j===i?{...v,cost:Number(e.target.value)}:v))}/></label><select aria-label={t('completed')} value={line.status} onChange={e=>patch('treatments',draft.treatments?.map((v,j)=>j===i?{...v,status:e.target.value as Treatment['status']}:v))}><option value="planned">{l(['مخطط','מתוכנן','Planned'])}</option><option value="completed">{l(['منفذ','בוצע','Completed'])}</option></select><button type="button" className="button button-outline" onClick={()=>patch('treatments',draft.treatments?.filter((_,j)=>j!==i))}>{t('remove')}</button></div>)}<button className="button button-outline" type="button" onClick={()=>patch('treatments',[...(draft.treatments??[]),{tooth:'',procedure:'',cost:0,status:'planned'}])}><Plus size={16}/>{t('procedure')}</button><p>{l(['إجمالي خطة العلاج (ليس تحصيلًا ماليًا)','סך תוכנית טיפול (אינו תקבול)','Treatment plan total (not a receipt)'])}: <b>₪ {(draft.treatments?.reduce((n,r)=>n+Math.round(r.cost*100),0)??0)/100}</b></p></section>}
 {specialty==='pediatrics'&&<section><h3>{l(['سجل التطعيمات','רישום חיסונים','Vaccination record'])}</h3>{draft.vaccines?.map((v,i)=><div className="specialty-plan-line" key={i}>{(['name','dose','date','nextDate'] as const).map(key=><label className="form-label" key={key}>{l(({name:['اللقاح','חיסון','Vaccine'],dose:['الجرعة / رقمها','מנה','Dose / number'],date:['تاريخ الإعطاء','תאריך מתן','Administered date'],nextDate:['الموعد القادم','מועד הבא','Next due date']} as Record<string,Label>)[key])}<input type={key==='date'||key==='nextDate'?'date':'text'} required={key==='name'||key==='date'} maxLength={key==='name'?200:60} value={v[key]} onChange={e=>patch('vaccines',draft.vaccines?.map((row,j)=>j===i?{...row,[key]:e.target.value}:row))}/></label>)}<button type="button" className="button button-outline" onClick={()=>patch('vaccines',draft.vaccines?.filter((_,j)=>j!==i))}>{t('remove')}</button></div>)}<button className="button button-outline" type="button" onClick={()=>patch('vaccines',[...(draft.vaccines??[]),{name:'',dose:'',date:clinicDate(),nextDate:''}])}><Plus size={16}/>{l(['إضافة تطعيم','הוספת חיסון','Add vaccination'])}</button></section>}
 {approver&&<ClinicalAiPanel lang={lang} onApply={text=>patch('notes',(draft.notes?draft.notes+'\n\n':'')+text)}/>}
 <div className="ops-fields"><label className="form-label ops-wide">{t('notes')}<textarea required maxLength={12000} value={draft.notes} onChange={e=>patch('notes',e.target.value)}/></label><label className="form-label ops-wide">{t('plan')}<textarea maxLength={12000} value={draft.plan} onChange={e=>patch('plan',e.target.value)}/></label><label className="form-label">{t('next')}<input type="date" value={draft.nextVisit} onChange={e=>patch('nextVisit',e.target.value)}/></label><label className="form-label">{l(['حالة السجل','מצב רשומה','Record status'])}<select value={draft.status} onChange={e=>patch('status',e.target.value)}><option value="draft">{t('draft')}</option>{approver&&<option value="completed">{t('completed')}</option>}</select></label></div>{approver&&<label className="specialty-share"><input type="checkbox" checked={draft.portalShared} onChange={e=>patch('portalShared',e.target.checked)}/>{t('share')}</label>}
 </fieldset><p className="clinic-settings-note">{t('review')}</p><div className="specialty-controls no-print">{writable&&<button className="button button-primary" type="submit" disabled={busy||!approver&&draft.status==='completed'}><Save size={16}/>{busy?'…':t('save')}</button>}<button className="button button-outline" type="button" onClick={()=>window.print()}><Printer size={16}/>{l(['طباعة','הדפסה','Print'])}</button></div></form>:<><div className="panel specialty-history"><div className="panel-heading"><h2>{t('history')}</h2><span>{history.length}</span></div>{history.length?history.map(row=><button className="specialty-history-row" key={row.id} onClick={()=>start(row)}><div><b>{row.name}</b><small>{row.date} · {row.status==='completed'?t('completed'):t('draft')}{row.nextVisit?' · '+t('next')+': '+row.nextVisit:''}</small></div><ChevronLeft size={18}/></button>):<p className="empty-state">{t('noVisits')}</p>}</div>{metricKeys.length>0&&<section className="panel specialty-trends"><h3>{t('growth')}</h3><p>{l(['اتجاه القياسات المدخلة؛ لا يعرض نسبًا مئوية أو تصنيفًا طبيًا للنمو.','מגמת מדידות בלבד, ללא אחוזוני גדילה או סיווג רפואי.','Trends of recorded measurements, without growth percentiles or medical classification.'])}</p><div className="specialty-trend-grid">{metricKeys.map(key=>{const m=definition.measures.find(v=>v.key===key)!;return <article key={key}><h4>{label(m.title,lang)} ({m.unit})</h4>{trend.some(v=>typeof v[key as keyof typeof v]==='number')?<ResponsiveContainer width="100%" height={210}><LineChart data={trend} margin={{left:0,right:12,top:10,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}} domain={['auto','auto']}/><Tooltip/><Line dataKey={key} stroke="#087e80" strokeWidth={2} dot isAnimationActive={false} connectNulls={false}/></LineChart></ResponsiveContainer>:<p>—</p>}</article>;})}</div></section>}</>}
 </div>;
}
