"use client";
import { useState } from "react";
import { authFetch } from "./auth-client";
import { CheckCircle2, CreditCard, RefreshCw } from "lucide-react";
type Language="ar"|"he"|"en";
type CheckoutCopy={title:string;desc:string;clinic:string;plan:string;term:string;month:string;year:string;plans:[string,string][];start:string;check:string;pending:string;paid:string;error:string;price:string};
const copy:Record<Language,CheckoutCopy>={ar:{title:"اشترك وادفع إلكترونيًا",desc:"اختر خطة عيادتك وأكمل الدفع الآمن عبر Qredit. بعد التحقق، يصدر النظام ترخيصك ويرسله إلى بريد حسابك.",clinic:"اسم العيادة",plan:"الخطة",term:"مدة الاشتراك",month:"شهري",year:"سنوي",plans:[["starter","البداية"],["professional","احترافية"],["business","الأعمال"],["medical_center","مركز طبي"]],start:"المتابعة إلى Qredit",check:"التحقق من الدفع",pending:"حالة الدفع قيد الانتظار. أعد التحقق بعد إتمام الدفع.",paid:"تم تأكيد الدفع وتفعيل حساب العيادة تلقائيًا. جارٍ فتح الحساب…",error:"تعذر إكمال العملية. أعد المحاولة.",price:"السعر بالشيقل"},he:{title:"הרשמה ותשלום מקוון",desc:"בחרו תוכנית והשלימו תשלום מאובטח דרך Qredit. לאחר האימות, הרישיון יישלח לדוא״ל החשבון.",clinic:"שם המרפאה",plan:"תוכנית",term:"תקופה",month:"חודשי",year:"שנתי",plans:[["starter","התחלה"],["professional","מקצועית"],["business","עסקית"],["medical_center","מרכז רפואי"]],start:"המשך ל-Qredit",check:"בדיקת תשלום",pending:"התשלום ממתין. בדקו שוב לאחר השלמתו.",paid:"התשלום אושר והמרפאה הופעלה אוטומטית. החשבון נפתח…",error:"לא ניתן להשלים. נסו שוב.",price:"מחיר בשקלים"},en:{title:"Subscribe and pay online",desc:"Choose your clinic plan and complete secure payment through Qredit. After verification, your license is issued and sent to your account email.",clinic:"Clinic name",plan:"Plan",term:"Billing term",month:"Monthly",year:"Annual",plans:[["starter","Starter"],["professional","Professional"],["business","Business"],["medical_center","Medical center"]],start:"Continue to Qredit",check:"Check payment",pending:"Payment is pending. Check again after completing it.",paid:"Payment confirmed and your clinic account is active. Opening your clinic…",error:"Could not complete this request. Try again.",price:"Price in ILS"}};
const prices:Record<string,[number,number]>={starter:[49,490],professional:[99,990],business:[179,1790],medical_center:[299,2990]};
export default function SubscriptionCheckoutPanel({lang}:{lang:Language}){const t=copy[lang], [clinic,setClinic]=useState(""),[plan,setPlan]=useState(()=>{if(typeof window==="undefined")return "professional";const selected=window.localStorage.getItem("clinic-selected-plan");return selected&&selected in prices?selected:"professional";}),[term,setTerm]=useState("monthly"),[paymentId,setPaymentId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[paid,setPaid]=useState(false);
 async function start(){setBusy(true);setMessage("");try{const r=await authFetch("/api/subscriber/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clinicName:clinic,plan,term,language:lang})});const d=await r.json() as {error?:string;paymentId?:string;checkoutUrl?:string};if(!r.ok||!d.paymentId||!d.checkoutUrl)throw new Error(d.error??t.error);setPaymentId(d.paymentId);sessionStorage.setItem("subscription-payment-id",d.paymentId);window.location.assign(d.checkoutUrl);}catch(e){setMessage(e instanceof Error?e.message:t.error);setBusy(false);}}
 async function check(id=paymentId){if(!id){setMessage(t.error);return;}setBusy(true);setMessage("");try{const r=await authFetch("/api/subscriber/checkout?paymentId="+encodeURIComponent(id));const d=await r.json() as {error?:string;status?:string;activated?:boolean};if(!r.ok)throw new Error(d.error??t.error);setPaid(d.status==="paid");setMessage(d.status==="paid"?t.paid:t.pending);if(d.activated)window.setTimeout(()=>window.location.reload(),900);}catch(e){setMessage(e instanceof Error?e.message:t.error);}finally{setBusy(false);}}
 const init=()=>{const id=typeof window!=="undefined"?sessionStorage.getItem("subscription-payment-id"):null;if(id){setPaymentId(id);void check(id);}};
 return <section className="panel subscriber-panel subscribe-panel"><div className="panel-heading"><div><h2><CreditCard size={19}/>{t.title}</h2><p>{t.desc}</p></div></div><div className="subscription-fields"><label className="form-label">{t.clinic}<input maxLength={160} value={clinic} onChange={e=>setClinic(e.target.value)}/></label><label className="form-label">{t.plan}<select value={plan} onChange={e=>setPlan(e.target.value)}>{t.plans.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="form-label">{t.term}<select value={term} onChange={e=>setTerm(e.target.value)}><option value="monthly">{t.month}</option><option value="annual">{t.year}</option></select></label><div className="subscribe-price"><small>{t.price}</small><strong>₪ {prices[plan][term==="monthly"?0:1]}</strong></div><button className="button button-primary" disabled={busy||clinic.trim().length<2} onClick={()=>void start()}><CreditCard size={16}/>{t.start}</button></div>{!paymentId&&<button className="button button-outline" disabled={busy} onClick={init}><RefreshCw size={15}/>{t.check}</button>}{paymentId&&<div className="verification-actions"><button className="button button-outline" disabled={busy} onClick={()=>void check()}><RefreshCw size={15}/>{t.check}</button></div>}{message&&<p role="status" className={paid?"subscriber-success":"subscriber-notice"}>{paid&&<CheckCircle2 size={16}/>} {message}</p>}</section>;
}
