"use client";
import { useEffect,useState } from "react";
import { Gift,Mail,Check,RefreshCw } from "lucide-react";
import { authFetch } from "./auth-client";
type Lang="ar"|"he"|"en";
const copy={
  ar:{trial:"تجربة مجانية لمدة شهر",intro:"اطلب حسابًا مجانيًا لمدة 30 يومًا، دون بطاقة دفع. تبدأ المدة بعد موافقة الإدارة، ولا يتجدد الاشتراك المدفوع تلقائيًا.",name:"اسم العيادة",agree:"أوافق على تجربة واحدة مجانية لحساب العيادة لمدة 30 يومًا من تاريخ الموافقة.",request:"إرسال طلب التجربة",pending:"طلبك بانتظار مراجعة الإدارة",approved:"التجربة مفعّلة",rejected:"لم تتم الموافقة على طلب التجربة",converted:"تم التحويل إلى اشتراك مدفوع",expiry:"نهاية التجربة",expired:"انتهت التجربة. فعّل اشتراكًا مدفوعًا لاستئناف العمل؛ بياناتك محفوظة.",reload:"الدخول إلى العيادة",refresh:"تحديث",admin:"طلبات الحسابات التجريبية",email:"البريد الإلكتروني",status:"الحالة",approve:"تفعيل 30 يومًا",reject:"رفض الطلب",empty:"لا توجد طلبات",error:"تعذر إكمال الطلب. حدّث الصفحة وتحقق من البيانات.",already:"تم تسجيل طلب سابق لهذا الحساب، أو لديه عيادة قائمة.",mail:"البريد الرسمي — Resend",mailNote:"رسائل معاملات رسمية بالعربية والعبرية والإنجليزية. تحتاج نطاق إرسال موثقًا في Resend؛ لا يمكن الإرسال باسم Gmail.",sender:"بريد المرسل على نطاقك",reply:"بريد الردود",key:"Resend API Key",enabled:"تفعيل الإرسال بعد توثيق النطاق",save:"حفظ الإعدادات",retry:"معالجة الرسائل المنتظرة",queued:"بانتظار الإرسال",accepted:"قبلها Resend للإرسال",failed:"تعذر الإرسال",blocked:"يتطلب مراجعة الإدارة",sending:"جارٍ الإرسال",saved:"تم حفظ الإعدادات المشفرة",delivery:"القبول لدى Resend لا يثبت وصول الرسالة إلى صندوق المستلم. سجل التسليم متاح في Resend.",trial_requested:"استلام طلب التجربة",trial_admin:"تنبيه الإدارة",trial_approved:"قبول التجربة",trial_rejected:"نتيجة المراجعة",subscription_created:"طلب اشتراك",payment_confirmed:"تأكيد الدفع والترخيص",setup:"النطاق غير مفعّل حاليًا. أضفه في Resend ثم اضبط سجلات DNS لدى مزوّد نطاقك.",requestSent:"تم تسجيل طلبك؛ تابع حالة المراجعة هنا."},
  he:{trial:"חודש ניסיון חינם",intro:"בקשו חשבון ל-30 יום ללא כרטיס תשלום. התקופה מתחילה אחרי אישור ההנהלה, ללא חידוש בתשלום אוטומטי.",name:"שם המרפאה",agree:"אני מסכים לניסיון אחד חינם של 30 יום ממועד האישור.",request:"שליחת בקשה",pending:"הבקשה ממתינה לאישור",approved:"הניסיון פעיל",rejected:"הניסיון לא אושר",converted:"החשבון שודרג למנוי בתשלום",expiry:"סוף הניסיון",expired:"הניסיון הסתיים. הפעילו מנוי בתשלום להמשך; הנתונים נשמרים.",reload:"כניסה למרפאה",refresh:"רענון",admin:"בקשות ניסיון",email:"דוא״ל",status:"סטטוס",approve:"הפעלת 30 יום",reject:"דחייה",empty:"אין בקשות",error:"הפעולה נכשלה. רעננו ובדקו את הפרטים.",already:"קיימת בקשה קודמת או מרפאה פעילה.",mail:"דוא״ל רשמי — Resend",mailNote:"הודעות חשבון בעברית, ערבית ואנגלית. נדרש דומיין מאומת ב-Resend; לא ניתן לשלוח בשם Gmail.",sender:"כתובת השולח בדומיין שלכם",reply:"כתובת לתשובות",key:"Resend API Key",enabled:"הפעלת משלוח לאחר אימות הדומיין",save:"שמירת הגדרות",retry:"עיבוד הודעות ממתינות",queued:"ממתין למשלוח",accepted:"התקבל למשלוח ב-Resend",failed:"המשלוח נכשל",blocked:"נדרשת בדיקת הנהלה",sending:"נשלח",saved:"ההגדרות המוצפנות נשמרו",delivery:"קבלה ב-Resend אינה אישור מסירה. בדקו את יומן המסירה ב-Resend.",trial_requested:"קבלת בקשת ניסיון",trial_admin:"הודעה להנהלה",trial_approved:"אישור ניסיון",trial_rejected:"תוצאת בדיקה",subscription_created:"בקשת מנוי",payment_confirmed:"אישור תשלום ורישיון",setup:"הדומיין טרם הופעל. הוסיפו אותו ב-Resend והגדירו DNS אצל ספק הדומיין.",requestSent:"בקשתכם נרשמה; עקבו אחר הסטטוס כאן."},
  en:{trial:"One month free trial",intro:"Request 30 days of free access without a payment card. The period starts after administration approval, with no automatic paid renewal.",name:"Clinic name",agree:"I agree to one free 30-day clinic trial starting from approval.",request:"Request free trial",pending:"Your request awaits administration review",approved:"Trial active",rejected:"Trial request not approved",converted:"Upgraded to a paid subscription",expiry:"Trial ends",expired:"The trial has ended. Activate a paid subscription to continue; your data is retained.",reload:"Enter clinic",refresh:"Refresh",admin:"Free trial requests",email:"Email",status:"Status",approve:"Activate 30 days",reject:"Reject",empty:"No requests",error:"Unable to complete the request. Refresh and check the details.",already:"This account already has a trial request or an existing clinic.",mail:"Official email — Resend",mailNote:"Transactional emails in Arabic, Hebrew and English. A verified sending domain is required in Resend; Gmail cannot be used as the sender.",sender:"Sender email on your domain",reply:"Reply-to email",key:"Resend API Key",enabled:"Enable sending after domain verification",save:"Save settings",retry:"Process pending emails",queued:"Queued",accepted:"Accepted by Resend",failed:"Sending failed",blocked:"Administration review needed",sending:"Sending",saved:"Encrypted settings saved",delivery:"Resend acceptance does not prove inbox delivery. Check the delivery log in Resend.",trial_requested:"Trial request receipt",trial_admin:"Administration notice",trial_approved:"Trial approved",trial_rejected:"Review result",subscription_created:"Subscription request",payment_confirmed:"Payment and license confirmation",setup:"The sending domain is not active yet. Add it in Resend, then configure DNS with your domain provider.",requestSent:"Your request was recorded; follow its review status here."},
};
type Trial={id:string;clinic_name:string;status:string;ends_at:string|null;email?:string;expired?:boolean};
type Message={id:string;kind:string;recipient:string;status:string;error_code:string|null};
type Reply={error?:string;trial?:Trial|null;trials?:Trial[];configured?:boolean;enabled?:boolean;fromEmail?:string;replyTo?:string;messages?:Message[]};
async function api(path:string,method="GET",body?:unknown){const response=await authFetch(path,{method,...(body?{headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{})});const data=await response.json() as Reply;if(!response.ok)throw new Error(data.error);return data;}
function date(value:string,lang:Lang){return new Intl.DateTimeFormat(lang,{dateStyle:"long",timeZone:"Asia/Hebron"}).format(new Date(value));}
export function TrialRequestPanel({lang}:{lang:Lang}){
  const t=copy[lang],[trial,setTrial]=useState<Trial|null>(null),[loaded,setLoaded]=useState(false),[name,setName]=useState(""),[agree,setAgree]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let mounted=true;api("/api/trial").then(d=>{if(mounted){setTrial(d.trial??null);setLoaded(true);}}).catch(()=>{if(mounted)setError(t.error);});return()=>{mounted=false;};},[t.error]);
  const refresh=async()=>{setBusy(true);try{const d=await api("/api/trial");setTrial(d.trial??null);setLoaded(true);}catch{setError(t.error);}finally{setBusy(false);}};
  const submit=async()=>{setBusy(true);setError("");try{await api("/api/trial","POST",{clinicName:name,language:lang,consent:agree});await refresh();}catch(e){setError(e instanceof Error&&["already_requested","existing_clinic"].includes(e.message)?t.already:t.error);}finally{setBusy(false);}};
  const expired=trial?.expired;
  return <section className="panel subscriber-panel"><div className="panel-heading"><div><h2><Gift size={20}/>{t.trial}</h2><p>{t.intro}</p></div></div>{loaded&&!trial&&<div className="subscriber-form"><label className="form-label">{t.name}<input maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="subscriber-check"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>{t.agree}</label><button className="button button-primary" disabled={busy||!agree||name.trim().length<2} onClick={()=>void submit()}>{t.request}</button></div>}{trial&&<><p className="subscriber-notice">{expired?t.expired:trial.status==="pending"?t.pending:trial.status==="approved"?t.approved:trial.status==="converted"?t.converted:t.rejected}</p>{trial.ends_at&&<p>{t.expiry}: {date(trial.ends_at,lang)}</p>}<div className="verification-actions"><button className="button button-outline" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>{t.refresh}</button>{trial.status==="approved"&&!expired&&<button className="button button-primary" onClick={()=>window.location.reload()}>{t.reload}</button>}</div></>}{error&&<p role="alert" className="error-banner">{error}</p>}</section>;
}
export function TrialAdminPanel({lang}:{lang:Lang}){
  const t=copy[lang],[trials,setTrials]=useState<Trial[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{api("/api/admin/trials").then(d=>setTrials(d.trials??[])).catch(()=>setError(t.error));},[t.error]);
  const review=async(id:string,action:string)=>{setBusy(true);setError("");try{await api("/api/admin/trials","PATCH",{id,action});const d=await api("/api/admin/trials");setTrials(d.trials??[]);}catch{setError(t.error);}finally{setBusy(false);}};
  return <section className="panel subscriber-panel"><div className="panel-heading"><div><h2>{t.admin}</h2><p>{t.intro}</p></div></div><div className="table-scroll"><table><thead><tr><th>{t.name}</th><th>{t.email}</th><th>{t.status}</th><th>{t.expiry}</th><th/></tr></thead><tbody>{trials.map(row=><tr key={row.id}><td>{row.clinic_name}</td><td dir="ltr">{row.email}</td><td>{row.expired?t.expired:row.status==="pending"?t.pending:row.status==="approved"?t.approved:row.status==="converted"?t.converted:t.rejected}</td><td>{row.ends_at?date(row.ends_at,lang):"—"}</td><td>{row.status==="pending"&&<div className="verification-actions"><button className="button button-primary small-button" disabled={busy} onClick={()=>void review(row.id,"approve")}><Check size={15}/>{t.approve}</button><button className="button button-outline small-button" disabled={busy} onClick={()=>void review(row.id,"reject")}>{t.reject}</button></div>}</td></tr>)}</tbody></table>{trials.length===0&&<div className="empty-state">{t.empty}</div>}</div>{error&&<p role="alert" className="error-banner">{error}</p>}</section>;
}
export function EmailSettingsPanel({lang}:{lang:Lang}){
  const t=copy[lang],[from,setFrom]=useState(""),[reply,setReply]=useState(""),[key,setKey]=useState(""),[enabled,setEnabled]=useState(false),[configured,setConfigured]=useState(false),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const apply=(d:Reply)=>{setFrom(d.fromEmail??"");setReply(d.replyTo??"");setEnabled(Boolean(d.enabled));setConfigured(Boolean(d.configured));setMessages(d.messages??[]);};
  useEffect(()=>{api("/api/admin/email-settings").then(d=>{setFrom(d.fromEmail??"");setReply(d.replyTo??"");setEnabled(Boolean(d.enabled));setConfigured(Boolean(d.configured));setMessages(d.messages??[]);}).catch(()=>setError(t.error));},[t.error]);
  const save=async()=>{setBusy(true);setError("");setSuccess("");try{await api("/api/admin/email-settings","PUT",{apiKey:key,fromEmail:from,replyTo:reply,enabled});setKey("");apply(await api("/api/admin/email-settings"));setSuccess(t.saved);}catch{setError(t.error);}finally{setBusy(false);}};
  const retry=async()=>{setBusy(true);setError("");try{await api("/api/admin/email-settings","POST",{});apply(await api("/api/admin/email-settings"));}catch{setError(t.error);}finally{setBusy(false);}};
  const label=(row:Message)=>row.status==="accepted"?t.accepted:row.status==="failed"?t.failed:row.status==="blocked"?t.blocked:row.status==="sending"?t.sending:t.queued;
  return <section className="panel subscriber-panel"><div className="panel-heading"><div><h2><Mail size={20}/>{t.mail}</h2><p>{t.mailNote}</p></div></div>{!configured&&<p className="subscriber-notice">{t.setup}</p>}<div className="sms-fields"><label className="form-label">{t.sender}<input type="email" dir="ltr" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="form-label">{t.reply}<input type="email" dir="ltr" value={reply} onChange={e=>setReply(e.target.value)}/></label><label className="form-label">{t.key}<input type="password" dir="ltr" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value.trim())}/></label><label className="subscriber-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>{t.enabled}</label><button className="button button-primary" disabled={busy||!from||!reply||(!configured&&!key)} onClick={()=>void save()}>{t.save}</button><button className="button button-outline" disabled={busy||!enabled||!configured} onClick={()=>void retry()}>{t.retry}</button></div>{error&&<p role="alert" className="error-banner">{error}</p>}{success&&<p role="status">{success}</p>}<p className="sms-note">{t.delivery}</p><div className="table-scroll"><table><thead><tr><th>{t.mail}</th><th>{t.email}</th><th>{t.status}</th></tr></thead><tbody>{messages.map(row=><tr key={row.id}><td>{t[row.kind as keyof typeof t]??row.kind}</td><td dir="ltr">{row.recipient}</td><td>{label(row)}{row.error_code&&<small className="table-sub">{row.error_code}</small>}</td></tr>)}</tbody></table></div></section>;
}
