import { z } from 'zod';
export type Language = 'ar'|'he'|'en';
export type Label = [string,string,string];
export const label = (v:Label,l:Language) => v[l==='ar'?0:l==='he'?1:2];
export type Field = {key:string;title:Label;type?:string;required?:boolean;options?:string[]};
const f=(key:string,title:Label,type='text',required=false,options?:string[]):Field=>({key,title,type,required,options});
export const modules:Record<string,{title:Label;fields:Field[];clinical?:boolean}>={

 feedback:{title:['رضا المرضى','שביעות רצון מטופלים','Patient satisfaction'],fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['موضوع التقييم','נושא משוב','Feedback subject'],'text',true),f('rating',['التقييم من 1 إلى 5','דירוג 1–5','Rating 1–5'],'number',true),f('date',['التاريخ','תאריך','Date'],'date',true),f('notes',['التعليق','תגובה','Comment'],'textarea'),f('status',['الحالة','סטטוס','Status'],'select',true,['pending','reviewed'])]},
 payroll:{title:['رواتب الموظفين','שכר עובדים','Staff payroll'],fields:[f('employeeId',['الموظف','עובד','Employee'],'employee',true),f('name',['الفترة / مرجع كشف الراتب','תקופה / אסמכתה','Period / payroll reference'],'text',true),f('date',['تاريخ الاستحقاق','תאריך תשלום','Due date'],'date',true),f('amount',['الراتب الإجمالي ₪','שכר ברוטו ₪','Gross salary ₪'],'number',true),f('deductions',['الخصومات ₪','ניכויים ₪','Deductions ₪'],'number',true),f('status',['الحالة','סטטוס','Status'],'select',true,['pending','paid']),f('notes',['ملاحظات','הערות','Notes'],'textarea')]},
 insurance:{title:['التأمين والمطالبات','ביטוח ותביעות','Insurance & claims'],fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['شركة التأمين','חברת ביטוח','Insurer'],'text',true),f('policyNumber',['رقم البوليصة','מספר פוליסה','Policy number'],'text',true),f('reference',['مرجع الموافقة','אסמכתת אישור','Authorization reference']),f('date',['تاريخ المطالبة','תאריך תביעה','Claim date'],'date',true),f('amount',['المبلغ المطلوب ₪','סכום תביעה ₪','Claim amount ₪'],'number',true),f('coveredAmount',['المبلغ المغطى ₪','סכום מכוסה ₪','Covered amount ₪'],'number',true),f('status',['الحالة','סטטוס','Status'],'select',true,['pending','approved','rejected','paid']),f('notes',['تفاصيل التغطية والمطالبة','פרטי כיסוי ותביעה','Coverage & claim details'],'textarea')]},
 waitlist:{title:['قائمة الانتظار','רשימת המתנה','Waitlist'],fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['الخدمة المطلوبة','שירות מבוקש','Requested service'],'text',true),f('employeeId',['الطبيب','רופא','Doctor'],'employee',true),f('date',['التاريخ المفضل','תאריך מועדף','Preferred date'],'date',true),f('start',['من الساعة','משעה','From time'],'time',true),f('end',['حتى الساعة','עד שעה','Until time'],'time',true),f('status',['الحالة','סטטוס','Status'],'select',true,['waiting','contacted','booked','cancelled']),f('notes',['ملاحظات التواصل','הערות קשר','Contact notes'],'textarea')]},
 packages:{title:['الباقات والجلسات','חבילות ומפגשים','Packages & sessions'],fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['اسم الباقة','שם חבילה','Package name'],'text',true),f('sessions',['عدد الجلسات','מספר מפגשים','Total sessions'],'number',true),f('usedSessions',['الجلسات المستخدمة','מפגשים שנוצלו','Used sessions'],'number',true),f('amount',['قيمة الباقة ₪','מחיר חבילה ₪','Package value ₪'],'number',true),f('date',['تاريخ البداية','תאריך התחלה','Start date'],'date',true),f('expires',['تاريخ الانتهاء','תוקף','Expiry date'],'date',true),f('status',['الحالة','סטטוס','Status'],'select',true,['active','completed','cancelled']),f('notes',['سجل الجلسات','רישום מפגשים','Session log'],'textarea')]},
 commissions:{title:['عمولات الأطباء','עמלות רופאים','Doctor commissions'],fields:[f('employeeId',['الطبيب','רופא','Doctor'],'employee',true),f('name',['الخدمة / مرجع الفاتورة','שירות / אסמכתת חשבונית','Service / invoice reference'],'text',true),f('date',['التاريخ','תאריך','Date'],'date',true),f('amount',['المبلغ المحصل ₪','סכום שנגבה ₪','Collected amount ₪'],'number',true),f('rate',['نسبة العمولة %','עמלה %','Commission rate %'],'number',true),f('status',['حالة التسوية','סטטוס תשלום','Settlement status'],'select',true,['pending','paid']),f('notes',['ملاحظات','הערות','Notes'],'textarea')]},
 consents:{title:['موافقات المرضى','הסכמות מטופלים','Patient consents'],clinical:true,fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['اسم الإجراء','שם הליך','Procedure name'],'text',true),f('date',['تاريخ الموافقة','תאריך הסכמה','Consent date'],'date',true),f('text',['نص الموافقة والمخاطر والبدائل','נוסח הסכמה סיכונים וחלופות','Consent text, risks & alternatives'],'textarea',true),f('signer',['اسم الموقّع / ولي الأمر','שם חותם / אפוטרופוס','Signer / guardian name'],'text',true),f('signature',['التوقيع الكتابي','חתימה מוקלדת','Typed signature']),f('status',['الحالة','סטטוס','Status'],'select',true,['draft','signed','withdrawn'])]},
 complaints:{title:['الشكاوى والمتابعة','תלונות ומעקב','Complaints & follow-up'],fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['موضوع الشكوى','נושא תלונה','Complaint subject'],'text',true),f('date',['التاريخ','תאריך','Date'],'date',true),f('priority',['الأولوية','עדיפות','Priority'],'select',true,['normal','urgent']),f('notes',['تفاصيل الشكوى','פרטי תלונה','Complaint details'],'textarea',true),f('resolution',['الإجراء المتخذ','פתרון','Resolution'],'textarea'),f('status',['الحالة','סטטוס','Status'],'select',true,['pending','processing','resolved'])]},
 specialty:{title:['سجلات التخصصات','רשומות מומחיות','Specialty records'],clinical:true,fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['عنوان السجل','כותרת רשומה','Record title'],'text',true),f('specialty',['التخصص','מומחיות','Specialty'],'select',true,['general','dental','obstetrics','pediatrics','dermatology','physiotherapy','ophthalmology']),f('date',['تاريخ الزيارة','תאריך ביקור','Visit date'],'date',true),f('notes',['الفحص والقياسات','בדיקה ומדידות','Examination & measurements'],'textarea',true),f('plan',['خطة العلاج والمتابعة','תוכנית טיפול ומעקב','Treatment & follow-up plan'],'textarea'),f('status',['الحالة','סטטוס','Status'],'select',true,['draft','completed'])]},
 doctors:{title:['الأطباء والموظفون','רופאים וצוות','Doctors & staff'],fields:[f('name',['الاسم','שם','Name'],'text',true),f('role',['الوظيفة','תפקיד','Position'],'select',true,['doctor','nurse','receptionist','accountant']),f('speciality',['التخصص','התמחות','Speciality']),f('phone',['الهاتف','טלפון','Phone']),f('email',['البريد','דוא״ל','Email'],'email'),f('duration',['مدة الكشف بالدقائق','משך תור בדקות','Appointment minutes'],'number',true),f('workingDays',['أيام الدوام: 0 أحد إلى 6 سبت (مثال 0,1,2,3,4)','ימי עבודה: 0 ראשון עד 6 שבת (למשל 0,1,2,3,4)','Working days: 0 Sun to 6 Sat (e.g. 0,1,2,3,4)']),f('start',['بداية الدوام','תחילת עבודה','Working hours start'],'time'),f('end',['نهاية الدوام','סיום עבודה','Working hours end'],'time'),f('branchId',['الفرع','סניף','Branch'],'branch'),f('schedule',['ملاحظات الدوام','הערות עבודה','Schedule notes'],'textarea'),f('status',['الحالة','סטטוס','Status'],'select',true,['active','inactive'])]},
 lab:{title:['المختبر والأشعة','מעבדה והדמיה','Lab & imaging'],clinical:true,fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['اسم الفحص','שם הבדיקה','Test name'],'text',true),f('kind',['النوع','סוג','Type'],'select',true,['lab','imaging']),f('date',['تاريخ الطلب','תאריך הזמנה','Requested date'],'date',true),f('result',['النتيجة والتقرير','תוצאה ודוח','Result & report'],'textarea'),f('status',['الحالة','סטטוס','Status'],'select',true,['requested','processing','ready','cancelled'])]},
 visits:{title:['الزيارات الطبية','ביקורים רפואיים','Medical visits'],clinical:true,fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['عنوان الزيارة','כותרת ביקור','Visit title'],'text',true),f('date',['التاريخ','תאריך','Date'],'date',true),f('diagnosis',['التشخيص','אבחנה','Diagnosis'],'textarea',true),f('notes',['الأعراض والفحص والخطة','תסמינים ובדיקה ותוכנית','Symptoms, examination & plan'],'textarea'),f('status',['الحالة','סטטוס','Status'],'select',true,['draft','completed'])]},
 prescriptions:{title:['الوصفات الطبية','מרשמים','Prescriptions'],clinical:true,fields:[f('patientId',['المريض','מטופל','Patient'],'patient',true),f('name',['عنوان الوصفة','כותרת מרשם','Prescription title'],'text',true),f('date',['التاريخ','תאריך','Date'],'date',true),f('medications',['الأدوية والجرعة والمدة','תרופות מינון ומשך','Medicines, dosage & duration'],'textarea',true),f('notes',['تعليمات','הנחיות','Instructions'],'textarea'),f('status',['الحالة','סטטוס','Status'],'select',true,['draft','issued','cancelled'])]},
 branches:{title:['الفروع','סניפים','Branches'],fields:[f('name',['اسم الفرع','שם סניף','Branch name'],'text',true),f('address',['العنوان','כתובת','Address'],'text',true),f('phone',['الهاتف','טלפון','Phone']),f('status',['الحالة','סטטוס','Status'],'select',true,['active','inactive'])]},
 suppliers:{title:['الموردون','ספקים','Suppliers'],fields:[f('name',['اسم المورد','שם ספק','Supplier name'],'text',true),f('phone',['الهاتف','טלפון','Phone']),f('email',['البريد','דוא״ל','Email'],'email'),f('address',['العنوان','כתובת','Address']),f('notes',['ملاحظات','הערות','Notes'],'textarea')]},
 expenses:{title:['المصروفات والمشتريات','הוצאות ורכש','Expenses & purchases'],fields:[f('name',['البيان','תיאור','Description'],'text',true),f('amount',['المبلغ ₪','סכום ₪','Amount ₪'],'number',true),f('date',['التاريخ','תאריך','Date'],'date',true),f('supplierId',['المورد','ספק','Supplier'],'supplier'),f('reference',['مرجع الفاتورة','אסמכתה','Invoice reference']),f('notes',['ملاحظات','הערות','Notes'],'textarea')]},
 attendance:{title:['الدوام والإجازات','נוכחות וחופשות','Attendance & leave'],fields:[f('employeeId',['الموظف','עובד','Employee'],'employee',true),f('name',['البيان','תיאור','Description'],'text',true),f('date',['التاريخ','תאריך','Date'],'date',true),f('kind',['النوع','סוג','Type'],'select',true,['attendance','leave']),f('start',['من الساعة','משעה','Start time'],'time'),f('end',['إلى الساعة','עד שעה','End time'],'time'),f('status',['الحالة','סטטוס','Status'],'select',true,['pending','approved','rejected'])]},
 services:{title:['الخدمات والأسعار','שירותים ומחירים','Services & prices'],fields:[f('name',['الخدمة','שירות','Service'],'text',true),f('amount',['السعر ₪','מחיר ₪','Price ₪'],'number',true),f('duration',['المدة بالدقائق','משך בדקות','Minutes'],'number',true),f('status',['الحالة','סטטוס','Status'],'select',true,['active','inactive'])]},
};
export const specialtyKeys=['general','dental','obstetrics','pediatrics','dermatology','physiotherapy','ophthalmology'] as const;
export type SpecialtyKey=typeof specialtyKeys[number];
export type ClinicalMeasure={key:string;title:Label;type:'number'|'text'|'date';unit?:string;min?:number;max?:number};
const measure=(key:string,title:Label,type:'number'|'text'|'date'='number',unit='',min=0,max=1000):ClinicalMeasure=>({key,title,type,unit,min,max});
export const specialties:Record<SpecialtyKey,{title:Label;description:Label;measures:ClinicalMeasure[]}>= {
 general:{title:['طب عام','רפואה כללית','General medicine'],description:['العلامات الحيوية والفحص وخطة المتابعة','מדדים חיוניים, בדיקה ומעקב','Vital signs, examination and follow-up'],measures:[measure('weight',['الوزن','משקל','Weight'],'number','kg',0.1,500),measure('height',['الطول','גובה','Height'],'number','cm',10,260),measure('temperature',['الحرارة','חום','Temperature'],'number','°C',25,45),measure('systolic',['الضغط الانقباضي','לחץ דם סיסטולי','Systolic BP'],'number','mmHg',30,300),measure('diastolic',['الضغط الانبساطي','לחץ דם דיאסטולי','Diastolic BP'],'number','mmHg',10,200),measure('pulse',['النبض','דופק','Pulse'],'number','bpm',10,300),measure('spo2',['تشبع الأكسجين','ריווי חמצן','SpO₂'],'number','%',0,100)]},
 dental:{title:['طب الأسنان','רפואת שיניים','Dentistry'],description:['مخطط الأسنان وخطة العلاج وتكلفة الإجراءات','תרשים שיניים, תוכנית טיפול ועלויות','Tooth chart, treatment plan and procedure costs'],measures:[measure('chiefComplaint',['الشكوى الرئيسية','תלונה עיקרית','Chief complaint'],'text'),measure('oralExam',['فحص الفم واللثة','בדיקת פה וחניכיים','Oral & periodontal examination'],'text'),measure('imagingReference',['مرجع الأشعة','אסמכתת הדמיה','Imaging reference'],'text')]},
 obstetrics:{title:['نسائية وتوليد','נשים ומיילדות','Obstetrics & gynecology'],description:['الحمل والزيارات ومتابعة الأم والجنين','הריון, ביקורים ומעקב אם ועובר','Pregnancy visits and maternal/fetal follow-up'],measures:[measure('lmp',['أول يوم لآخر دورة','יום ראשון לווסת אחרונה','First day of last menstrual period'],'date'),measure('confirmedDueDate',['موعد الولادة المعتمد من الطبيب','מועד לידה מאושר','Clinician-confirmed due date'],'date'),measure('gravida',['عدد مرات الحمل','מספר הריונות','Gravida'],'number','',0,30),measure('para',['عدد الولادات','מספר לידות','Para'],'number','',0,30),measure('weight',['الوزن','משקל','Weight'],'number','kg',0.1,500),measure('systolic',['الضغط الانقباضي','לחץ דם סיסטולי','Systolic BP'],'number','mmHg',30,300),measure('diastolic',['الضغط الانبساطي','לחץ דם דיאסטולי','Diastolic BP'],'number','mmHg',10,200),measure('fetalHeartRate',['نبض الجنين','דופק עובר','Fetal heart rate'],'number','bpm',0,300),measure('ultrasound',['نتائج السونار','תוצאות אולטרסאונד','Ultrasound findings'],'text')]},
 pediatrics:{title:['طب الأطفال','רפואת ילדים','Pediatrics'],description:['القياسات عبر الزيارات والتطور والتطعيمات','מדידות לאורך ביקורים, התפתחות וחיסונים','Measurements over time, development and vaccinations'],measures:[measure('weight',['الوزن','משקל','Weight'],'number','kg',0.1,300),measure('height',['الطول','גובה','Height'],'number','cm',10,230),measure('headCircumference',['محيط الرأس','היקף ראש','Head circumference'],'number','cm',10,80),measure('temperature',['الحرارة','חום','Temperature'],'number','°C',25,45),measure('development',['التطور الحركي واللغوي','התפתחות מוטורית ושפתית','Motor & language development'],'text'),measure('feeding',['التغذية','תזונה','Feeding'],'text')]},
 dermatology:{title:['جلدية وتجميل','עור ואסתטיקה','Dermatology & aesthetics'],description:['مناطق العلاج والجلسات ومراجع صور قبل وبعد','אזורי טיפול, מפגשים ותמונות לפני/אחרי','Treatment areas, sessions and before/after file references'],measures:[measure('area',['منطقة العلاج','אזור טיפול','Treatment area'],'text'),measure('lesion',['وصف الحالة الجلدية','תיאור נגע','Skin findings'],'text'),measure('procedure',['الإجراء / الجهاز','הליך / מכשיר','Procedure / device'],'text'),measure('settings',['إعدادات الجهاز المعتمدة','הגדרות מכשיר','Clinician-recorded device settings'],'text'),measure('beforeFileId',['مرجع صورة قبل','אסמכתת תמונה לפני','Before image file ID'],'text'),measure('afterFileId',['مرجع صورة بعد','אסמכתת תמונה אחרי','After image file ID'],'text'),measure('adverseEffects',['الأعراض بعد الجلسة','תופעות לאחר טיפול','Post-treatment effects'],'text')]},
 physiotherapy:{title:['علاج طبيعي','פיזיותרפיה','Physiotherapy'],description:['الألم ومدى الحركة والتمارين وتقدم الجلسات','כאב, טווח תנועה, תרגילים והתקדמות','Pain, range of motion, exercises and session progress'],measures:[measure('painArea',['منطقة الألم','אזור כאב','Pain area'],'text'),measure('painScore',['شدة الألم','רמת כאב','Pain score'],'number','0–10',0,10),measure('rangeOfMotion',['مدى الحركة','טווח תנועה','Range of motion'],'number','°',0,360),measure('functionalAssessment',['التقييم الوظيفي','הערכה תפקודית','Functional assessment'],'text'),measure('exercises',['التمارين المنزلية','תרגילי בית','Home exercises'],'text'),measure('progress',['تقدم الحالة','התקדמות','Progress'],'text')]},
 ophthalmology:{title:['طب العيون','רפואת עיניים','Ophthalmology'],description:['حدة البصر وضغط العين والانكسار لكل عين','חדות ראייה, לחץ עין ותשבורת לכל עין','Visual acuity, intraocular pressure and refraction by eye'],measures:[measure('vaRight',['حدة البصر يمين','חדות ראייה ימין','Right visual acuity'],'text'),measure('vaLeft',['حدة البصر يسار','חדות ראייה שמאל','Left visual acuity'],'text'),measure('iopRight',['ضغط العين يمين','לחץ עין ימין','Right IOP'],'number','mmHg',0,100),measure('iopLeft',['ضغط العين يسار','לחץ עין שמאל','Left IOP'],'number','mmHg',0,100),measure('sphereRight',['Sphere يمين','Sphere ימין','Right sphere'],'number','D',-40,40),measure('sphereLeft',['Sphere يسار','Sphere שמאל','Left sphere'],'number','D',-40,40),measure('cylinderRight',['Cylinder يمين','Cylinder ימין','Right cylinder'],'number','D',-20,20),measure('cylinderLeft',['Cylinder يسار','Cylinder שמאל','Left cylinder'],'number','D',-20,20),measure('axisRight',['Axis يمين','Axis ימין','Right axis'],'number','°',0,180),measure('axisLeft',['Axis يسار','Axis שמאל','Left axis'],'number','°',0,180),measure('fundus',['فحص قاع العين','בדיקת קרקעית העין','Fundus examination'],'text')]}
};
export const toothStates:Record<string,Label>={healthy:['سليم','תקין','Healthy'],caries:['تسوس','עששת','Caries'],filled:['حشوة','סתימה','Filled'],missing:['مفقود','חסר','Missing'],crown:['تاج','כתר','Crown'],root_canal:['علاج عصب','טיפול שורש','Root canal'],implant:['زرعة','שתל','Implant']};
export function specialtySchema(key:SpecialtyKey){
 const shape:Record<string,z.ZodTypeAny>={};
 for(const m of specialties[key].measures){const v=m.type==='number'?z.number().finite().min(m.min??0).max(m.max??1000):m.type==='date'?z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v):z.string().trim().max(2000);shape[m.key]=v.optional();}
 return z.object(shape).strict();
}
export function estimatedPregnancy(lmp:string,onDate:string){const a=Date.parse(lmp+'T12:00:00Z'),b=Date.parse(onDate+'T12:00:00Z');if(!Number.isFinite(a)||!Number.isFinite(b)||b<a)return null;const days=Math.floor((b-a)/86400000);return {weeks:Math.floor(days/7),days:days%7,dueDate:new Date(a+280*86400000).toISOString().slice(0,10)};}

export function canAccess(role:string,module:string,write=false){
 if(role==='clinic_admin')return true;
 if(module==='portal_access')return role==='doctor';
 if(module==='booking_requests')return ['doctor','receptionist'].includes(role);
 const access:Record<string,string[]>={doctor:['queue','consents','specialty','booking_requests','portal_access','dashboard','patients','appointments','doctors','visits','lab','prescriptions','files','services','inventory','branches'],nurse:['queue','consents','specialty','booking_requests','portal_access','dashboard','patients','appointments','doctors','visits','lab','files','inventory','branches'],receptionist:['feedback','queue','insurance','waitlist','packages','complaints','booking_requests','portal_access','dashboard','patients','appointments','doctors','billing','services','branches'],accountant:['payroll','doctors','insurance','commissions','packages','dashboard','billing','reports','inventory','suppliers','expenses','services','branches']};
 if(!access[role]?.includes(module))return false;
 if(write && role==='nurse' && module==='consents')return false;
 if(write && ['branches','services','doctors'].includes(module))return false;
 if(write && role==='nurse' && module==='patients')return false;
 if(write && role==='doctor' && module==='inventory')return false;
 return true;
}
export function validateRecord(module:string,input:unknown){
 const def=modules[module];if(!def)throw new Error('Unknown module');
 const shape:Record<string,z.ZodTypeAny>={};
 for(const field of def.fields){
  let schema:z.ZodTypeAny=field.type==='number'?z.coerce.number().finite().min(0).max(1000000):z.string().trim().max(field.type==='textarea'?12000:300);
  if(field.type==='number'&&field.key==='duration')schema=z.coerce.number().int().min(5).max(480);
  if(field.options)schema=z.enum(field.options as [string,...string[]]);
  if(['patient','employee','supplier'].includes(field.type??'')&&field.required)schema=z.string().uuid();
  if(field.key==='workingDays')schema=z.string().regex(/^(?:[0-6](?:,[0-6])*)?$/);
  if(field.type==='time')schema=z.union([z.literal(''),z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)]);
  if(field.key==='amount')schema=z.coerce.number().min(0).max(1000000).refine(v=>Math.abs(v*100-Math.round(v*100))<0.000001);
  if(field.type==='date')schema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
  if(field.type==='email')schema=z.union([z.literal(''),z.string().email().max(254)]);
  if(field.required&&field.type!=='number'&&!field.options)schema=schema.refine(v=>typeof v==='string'&&v.length>0);
  shape[field.key]=field.required?schema:schema.optional();
 }
 if(module==='lab')shape.sampleCode=z.string().regex(/^\d{13}$/).optional();
 if(['visits','lab','prescriptions'].includes(module))shape.portalShared=z.boolean().optional();
 if(module==='specialty'){
  const key=z.enum(specialtyKeys).parse((input as Record<string,unknown>)?.specialty);
  shape.findings=specialtySchema(key).optional();
  shape.dentition=z.enum(['permanent','primary']).optional();
  shape.teeth=z.record(z.string().regex(/^(?:[1-4][1-8]|[5-8][1-5])$/),z.enum(['healthy','caries','filled','missing','crown','root_canal','implant'])).optional();
  shape.treatments=z.array(z.object({tooth:z.string().regex(/^(?:[1-4][1-8]|[5-8][1-5])?$/),procedure:z.string().trim().min(1).max(300),cost:z.number().finite().min(0).max(1000000).refine(v=>Math.abs(v*100-Math.round(v*100))<0.000001),status:z.enum(['planned','completed'])}).strict()).max(100).optional();
  shape.vaccines=z.array(z.object({name:z.string().trim().min(1).max(200),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),dose:z.string().trim().max(60),nextDate:z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/)])}).strict()).max(100).optional();
  shape.nextVisit=z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/)]).optional();
  shape.portalShared=z.boolean().optional();
 }
 const result=z.object(shape).strict().parse(input) as Record<string,string|number>;
 const issue=(key:string,message:string)=>{throw new z.ZodError([{code:'custom',path:[key],message}]);};
 if(module==='feedback'&&(!Number.isInteger(result.rating)||Number(result.rating)<1||Number(result.rating)>5))issue('rating','Rating must be 1 to 5');
 if(module==='payroll'&&Number(result.deductions)>Number(result.amount))issue('deductions','Deductions exceed gross salary');
 if(module==='insurance'&&Number(result.coveredAmount)>Number(result.amount))issue('coveredAmount','Coverage exceeds claim');
 if(module==='commissions'&&Number(result.rate)>100)issue('rate','Rate must be between 0 and 100');
 if(module==='packages'){
  if(!Number.isInteger(result.sessions)||Number(result.sessions)<1||!Number.isInteger(result.usedSessions)||Number(result.usedSessions)>Number(result.sessions))issue('usedSessions','Invalid session balance');
  if(String(result.expires)<String(result.date))issue('expires','Expiry precedes start');
 }
 if(module==='specialty'&&result.specialty!=='dental'&&(result.teeth&&Object.keys(result.teeth).length||result.treatments&&(result.treatments as unknown as unknown[]).length))issue('teeth','Dental data belongs to dentistry');
 if(module==='specialty'&&result.specialty!=='pediatrics'&&result.vaccines&&(result.vaccines as unknown as unknown[]).length)issue('vaccines','Vaccinations belong to pediatrics');
 if(module==='consents'&&result.status==='signed'&&!String(result.signature??'').trim())issue('signature','Signature required');
 if(result.start&&result.end&&result.end<=result.start)throw new z.ZodError([{code:'custom',message:'End must follow start',path:['end']}]);return result;
}
export function moneyMinor(value:unknown){const n=Number(value);if(!Number.isFinite(n)||n<0||n>1000000||Math.abs(n*100-Math.round(n*100))>0.000001)throw new Error('Use a valid amount with at most two decimals');return Math.round(n*100);}
export function invoiceTotals(lines:{name:string;qty:number;price:number}[],tax:number){
 if(!Array.isArray(lines)||!lines.length||lines.length>50||!Number.isInteger(tax)||tax<0||tax>10000)throw new Error('Invalid invoice');
 let subtotal=0;for(const l of lines){if(typeof l.name!=='string'||!l.name.trim()||l.name.length>300||!Number.isInteger(l.qty)||l.qty<1||l.qty>10000)throw new Error('Invalid invoice line');subtotal+=moneyMinor(l.price)*l.qty;}
 if(subtotal>100000000)throw new Error('Invoice exceeds limit');const taxAmount=Math.round(subtotal*tax/10000);return {subtotal,taxAmount,total:subtotal+taxAmount};
}
export function csvCell(value:unknown){let s=String(value??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}

// EAN-13 is used here only as an internal numeric lab-sample label.
export function ean13(base:string){if(!/^\d{12}$/.test(base))throw new Error('12 digits required');const sum=[...base].reduce((n,c,i)=>n+Number(c)*(i%2?3:1),0);return base+String((10-sum%10)%10);}
export function ean13Bits(code:string){if(!/^\d{13}$/.test(code)||ean13(code.slice(0,12))!==code)throw new Error('Invalid barcode checksum');const a=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'];const b=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'];const parity=['AAAAAA','AABABB','AABBAB','AABBBA','ABAABB','ABBAAB','ABBBAA','ABABAB','ABABBA','ABBABA'][Number(code[0])];return '101'+[...code.slice(1,7)].map((c,i)=>(parity[i]==='A'?a:b)[Number(c)]).join('')+'01010'+[...code.slice(7)].map(c=>[...a[Number(c)]].map(v=>v==='1'?'0':'1').join('')).join('')+'101';}
