import { escapeHtml, type MailLanguage } from "./subscriber-policy";
export type MailKind = "trial_requested" | "trial_admin" | "trial_approved" | "trial_rejected" | "subscription_created" | "payment_confirmed";
export type SubscriberMessage = { clinicName:string; language:MailLanguage; expiresAt?:string; amountIls?:number; licenseKey?:string };
const copy = {
  ar:{brand:"عيادتي",hello:"تحية طيبة،",footer:"فريق إدارة برنامج عيادتي · هذه رسالة متعلقة بحسابك واشتراكك.",button:"الدخول إلى النظام",trial_requested:["استلام طلب التجربة المجانية","استلمنا طلب حساب تجريبي لعيادتكم. التجربة مجانية لمدة 30 يومًا، وتبدأ بعد موافقة الإدارة. لا تحتاج بطاقة دفع ولا يتحول الحساب تلقائيًا إلى اشتراك مدفوع."],trial_admin:["طلب حساب تجريبي جديد","ورد طلب حساب تجريبي جديد. يرجى مراجعته في إدارة الاشتراكات."],trial_approved:["تم تفعيل تجربتكم المجانية","وافقنا على طلبكم وفعّلنا حساب العيادة لمدة 30 يومًا دون رسوم. يمكنكم الدخول الآن. ينتهي الوصول التجريبي في التاريخ الموضح أدناه، ويمكنكم الانتقال إلى اشتراك مدفوع مع الاحتفاظ بالبيانات."],trial_rejected:["تحديث طلب الحساب التجريبي","بعد مراجعة الطلب، لم تتم الموافقة على التجربة المجانية. يمكنكم الرد على هذه الرسالة للاستفسار عن خيارات الاشتراك."],subscription_created:["تفاصيل طلب الاشتراك","تم تسجيل طلب الاشتراك لعيادتكم. الطلب بانتظار تأكيد الدفع من الإدارة؛ تسجيل الطلب لا يعني أن الدفع تم. سنرسل رقم الترخيص بعد تأكيده."],payment_confirmed:["تأكيد الدفع وإصدار الترخيص","تم تأكيد دفع الاشتراك وإصدار رقم ترخيص خاص بعيادتكم. سجلوا الدخول بالبريد الذي استلم هذه الرسالة وأدخلوا الرقم لتفعيل الاشتراك. احتفظوا بالرقم بشكل آمن."],clinic:"العيادة",expiry:"نهاية الصلاحية",amount:"قيمة الاشتراك",key:"رقم الترخيص"},
  he:{brand:"عيادتي",hello:"שלום רב,",footer:"צוות ניהול המערכת · הודעה לגבי החשבון והמנוי שלכם.",button:"כניסה למערכת",trial_requested:["בקשת הניסיון התקבלה","בקשתכם לניסיון חינם התקבלה. הניסיון נמשך 30 יום ומתחיל לאחר אישור ההנהלה. אין צורך בכרטיס תשלום ואין חיוב אוטומטי."],trial_admin:["בקשת ניסיון חדשה","התקבלה בקשת ניסיון חדשה. בדקו אותה בניהול המנויים."],trial_approved:["הניסיון החינמי הופעל","בקשתכם אושרה והמרפאה הופעלה ל-30 יום ללא תשלום. ניתן להיכנס עכשיו. לאחר התאריך שלהלן נדרש מנוי בתשלום; הנתונים נשמרים בעת השדרוג."],trial_rejected:["עדכון בקשת ניסיון","לאחר בדיקת הבקשה, הניסיון החינמי לא אושר. השיבו להודעה למידע על אפשרויות המנוי."],subscription_created:["פרטי בקשת המנוי","בקשת המנוי נרשמה וממתינה לאישור התשלום. רישום הבקשה אינו אישור תשלום. הרישיון יישלח לאחר האישור."],payment_confirmed:["אישור תשלום ורישיון","התשלום אושר והונפק רישיון למרפאה. התחברו באמצעות כתובת הדוא״ל שקיבלה הודעה זו והזינו את הקוד להפעלה. שמרו עליו בצורה מאובטחת."],clinic:"מרפאה",expiry:"תום תוקף",amount:"סכום המנוי",key:"קוד רישיון"},
  en:{brand:"Ayadati",hello:"Dear subscriber,",footer:"Ayadati program administration · A transactional message about your account and subscription.",button:"Sign in to your account",trial_requested:["Free trial request received","We received your clinic’s free trial request. The 30-day trial starts after administration approval. No payment card is needed and there is no automatic paid renewal."],trial_admin:["New free trial request","A new clinic trial request is waiting for review in subscription administration."],trial_approved:["Your free trial is active","Your clinic has been approved for 30 days of free access. You can sign in now. Trial access ends on the date below. Upgrade to a paid subscription to continue while keeping your data."],trial_rejected:["Update on your trial request","After review, your free trial request was not approved. Reply to this email for information about subscription options."],subscription_created:["Subscription request details","Your clinic’s subscription request has been recorded and is awaiting payment confirmation. Creating a request does not confirm payment. The license will be emailed after administration confirms payment."],payment_confirmed:["Payment confirmed and license issued","Your subscription payment has been confirmed and a unique clinic license has been issued. Sign in using the email receiving this message and enter the license code to activate. Keep it secure."],clinic:"Clinic",expiry:"Valid until",amount:"Subscription amount",key:"License code"},
} as const;
export function subscriberEmail(kind:MailKind,data:SubscriberMessage) {
  const t=copy[data.language], [subject,intro]=t[kind];
  const details:[[string,string],...Array<[string,string]>]=[[t.clinic,data.clinicName]];
  if(data.expiresAt) details.push([t.expiry,new Intl.DateTimeFormat(data.language,{dateStyle:"long",timeZone:"Asia/Hebron"}).format(new Date(data.expiresAt))]);
  if(data.amountIls!==undefined) details.push([t.amount,`${data.amountIls} ILS ₪`]);
  if(data.licenseKey) details.push([t.key,data.licenseKey]);
  const url="https://clinic-ops-palestine.nbeelsalah4.chatgpt.site/";
  const text=[t.hello,intro,...details.map(([k,v])=>`${k}: ${v}`),`${t.button}: ${url}`,t.footer].join("\n\n");
  const html=`<!doctype html><html lang="${data.language}" dir="${data.language==="en"?"ltr":"rtl"}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(subject)}</title></head><body style="margin:0;background:#f1f6f6;font-family:Arial,sans-serif;color:#183434"><table role="presentation" width="100%"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" style="max-width:600px;background:white;border-radius:16px"><tr><td style="padding:32px"><div style="color:#087966;font-size:25px;font-weight:bold">${t.brand}</div><h1 style="font-size:22px;line-height:1.6">${escapeHtml(subject)}</h1><p>${t.hello}</p><p style="line-height:1.9">${escapeHtml(intro)}</p>${details.map(([k,v])=>`<p style="line-height:1.8"><strong>${escapeHtml(k)}:</strong> <span dir="auto">${escapeHtml(v)}</span></p>`).join("")}<p style="margin:28px 0"><a href="${url}" style="background:#087966;color:white;padding:14px 22px;text-decoration:none;border-radius:8px;display:inline-block">${t.button}</a></p><hr style="border:0;border-top:1px solid #e2ebeb"><p style="font-size:12px;line-height:1.8;color:#536d6d">${t.footer}</p></td></tr></table></td></tr></table></body></html>`;
  return {subject,text,html};
}
