import { env } from "cloudflare:workers";
import { getSupabaseUser, sha256 } from "../../../../lib/clinic-runtime";
import { mailLanguage } from "../../../../lib/subscriber-policy";
import { qreditGet, qreditPost, qreditRecords, qreditToken } from "../../../../lib/qredit";
import { moneyMinor } from "../../../../lib/ops-model";

const plans={starter:{monthly:49,annual:490},professional:{monthly:99,annual:990},business:{monthly:179,annual:1790},medical_center:{monthly:299,annual:2990}} as const;
type Plan=keyof typeof plans;
function response(body:unknown,status=200){return Response.json(body,{status,headers:{"Cache-Control":"no-store"}});}
function field(record:Record<string,unknown>,...names:string[]){for(const name of names){const value=record[name];if(typeof value==="string"&&value)return value;}return "";}
function licenseKey(){const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",bytes=crypto.getRandomValues(new Uint8Array(20)),raw=Array.from(bytes,b=>alphabet[b&31]).join("");return `AYD-${raw.slice(0,5)}-${raw.slice(5,10)}-${raw.slice(10,15)}-${raw.slice(15,20)}`;}
function providerError(){return env.QREDIT_API_KEY&&env.QREDIT_SECRET_KEY?"تعذر إنشاء الدفع عبر Qredit. أعد المحاولة لاحقًا.":"بوابة دفع الاشتراكات غير مهيأة بعد.";}

export async function POST(request:Request){
 const user=await getSupabaseUser(request);if(!user)return response({error:"سجّل الدخول ببريد مؤكد للمتابعة."},401);const db=env.DB;if(!db)return response({error:"قاعدة البيانات غير متاحة."},503);
 let body:{clinicName?:string;plan?:string;term?:string;language?:string};try{body=await request.json() as typeof body;}catch{return response({error:"بيانات الطلب غير صالحة."},400);}
 const name=body.clinicName?.trim().slice(0,160)??"",plan=body.plan as Plan,term=body.term;
 if(name.length<2||!Object.hasOwn(plans,plan)||!(term==="monthly"||term==="annual"))return response({error:"أدخل اسم العيادة واختر خطة ومدة صحيحتين."},400);
 if(await db.prepare("SELECT id FROM platform_users WHERE user_id=?").bind(user.userId).first())return response({error:"حساب إدارة البرنامج لا يشتري اشتراك عيادة."},403);
 if(await db.prepare("SELECT id FROM clinic_memberships WHERE user_id=? AND active=1 LIMIT 1").bind(user.userId).first())return response({error:"يوجد حساب عيادة مرتبط بهذا المستخدم بالفعل."},409);if(await db.prepare("SELECT id FROM licenses l JOIN subscriptions s ON s.id=l.subscription_id WHERE s.created_by=? AND s.payment_status='paid' AND l.status IN ('issued','active') LIMIT 1").bind(user.userId).first())return response({error:"يوجد اشتراك مدفوع بالفعل لهذا الحساب."},409);
 const amount=plans[plan][term],language=mailLanguage(body.language),existing=await db.prepare("SELECT p.id,p.checkout_url,p.status FROM qredit_subscription_payments p JOIN subscriptions s ON s.id=p.subscription_id WHERE p.user_id=? AND s.payment_status='pending' AND p.status IN ('creating','pending') ORDER BY p.created_at DESC LIMIT 1").bind(user.userId).first<{id:string;checkout_url:string|null;status:string}>();
 if(existing?.checkout_url)return response({paymentId:existing.id,checkoutUrl:existing.checkout_url,status:existing.status});
 const subscriptionId=crypto.randomUUID(),paymentId=crypto.randomUUID(),clientReference="sub-"+crypto.randomUUID();
 try{
  const trial=await db.prepare("SELECT id FROM trial_requests WHERE user_id=? AND status IN ('pending','approved') LIMIT 1").bind(user.userId).first();if(trial)return response({error:"لديك طلب تجربة أو تجربة مفعلة بالفعل. راجع حالة الطلب أولًا."},409);
  await db.batch([db.prepare("INSERT INTO subscriptions (id,clinic_name,contact_email,language,plan,term,amount_ils,created_by) VALUES (?,?,?,?,?,?,?,?)").bind(subscriptionId,name,user.email,language,plan,term,amount,user.userId),db.prepare("INSERT INTO qredit_subscription_payments (id,subscription_id,user_id,client_reference,amount_ils,status) VALUES (?,?,?,?,?,'creating')").bind(paymentId,subscriptionId,user.userId,clientReference,amount)]);
  const token=await qreditToken(),cents=moneyMinor(amount);const orderResult=await qreditPost("/orders",{amountCents:cents,currencyCode:"ILS",clientReference,items:[{name:`Clinic plan ${plan}`,quantity:1,unitPriceCents:cents}]},token),order=qreditRecords(orderResult)[0]??orderResult,orderReference=field(order,"orderReference","reference");if(!orderReference)throw new Error("provider");
  const payResult=await qreditPost("/paymentRequests",{orderReference,amountCents:cents,currencyCode:"ILS",lockOrderWhenPaid:true,expiration:30,paymentChannels:[{code:"CSAB"},{code:"esadad_biller"},{code:"NC-QR"}],customerInfo:{name,email:user.email}},token),payment=qreditRecords(payResult)[0]??payResult,paymentReference=field(payment,"reference","paymentReference"),checkoutUrl=field(payment,"url","checkoutUrl","paymentUrl");
  if(!paymentReference||!checkoutUrl)throw new Error("provider");const target=new URL(checkoutUrl);if(target.protocol!=="https:"||!(target.hostname==="qredit.tech"||target.hostname.endsWith(".qredit.tech")))throw new Error("provider");
  await db.prepare("UPDATE qredit_subscription_payments SET order_reference=?,payment_reference=?,checkout_url=?,provider_status=?,status='pending',updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").bind(orderReference,paymentReference,target.toString(),field(payment,"paymentRequestStatus","status")||"PENDING_PAYMENT",paymentId,user.userId).run();
  return response({paymentId,checkoutUrl:target.toString(),status:"pending",amountIls:amount,currency:"ILS"},201);
 }catch{await db.prepare("UPDATE qredit_subscription_payments SET status='failed',provider_status='PROVIDER_ERROR',updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").bind(paymentId,user.userId).run();return response({error:providerError()},502);}
}

export async function GET(request:Request){
 const user=await getSupabaseUser(request);if(!user)return response({error:"سجّل الدخول للمتابعة."},401);const db=env.DB;if(!db)return response({error:"قاعدة البيانات غير متاحة."},503);
 const id=new URL(request.url).searchParams.get("paymentId")??"";const payment=await db.prepare("SELECT p.*,s.plan,s.term,s.clinic_name,s.contact_email,s.language,s.payment_status FROM qredit_subscription_payments p JOIN subscriptions s ON s.id=p.subscription_id WHERE p.id=? AND p.user_id=?").bind(id,user.userId).first<{id:string;subscription_id:string;user_id:string;client_reference:string;order_reference:string|null;payment_reference:string|null;amount_ils:number;status:string;plan:Plan;term:"monthly"|"annual";clinic_name:string;contact_email:string;language:string;payment_status:string}>();
 if(!payment)return response({error:"طلب الدفع غير موجود."},404);if(payment.status==="paid"||payment.payment_status==="paid")return response({status:"paid",activated:true,clinicName:payment.clinic_name});if(payment.status!=="pending"||!payment.payment_reference||!payment.order_reference)return response({status:payment.status});
 try{
  const token=await qreditToken(),paymentResult=qreditRecords(await qreditGet("/paymentRequests",{reference:payment.payment_reference},token))[0];if(!paymentResult)return response({error:"لم يصل رد حالة الدفع من البوابة."},502);
  const payStatus=field(paymentResult,"paymentRequestStatus","status");if(payStatus!=="PAID"){const status=payStatus==="CANCELLED"?"cancelled":payStatus==="EXPIRED"?"expired":"pending";await db.prepare("UPDATE qredit_subscription_payments SET provider_status=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=? AND status='pending'").bind(payStatus||"UNKNOWN",status,id,user.userId).run();return response({status});}
  const order=qreditRecords(await qreditGet("/orders",{orderReference:payment.order_reference},token))[0];if(!order)return response({error:"تعذر التحقق من الطلب."},502);
  const cents=moneyMinor(payment.amount_ils),valid=field(paymentResult,"reference","paymentReference")===payment.payment_reference&&field(paymentResult,"orderReference")===payment.order_reference&&field(order,"orderReference","reference")===payment.order_reference&&field(order,"clientReference")===payment.client_reference&&Number(paymentResult.amountCents)===cents&&String(paymentResult.currencyCode)==="ILS"&&["PAID","COMPLETED"].includes(field(order,"orderStatus","status"))&&Number(order.amountCents)===cents&&String(order.currencyCode)==="ILS";if(!valid)return response({error:"لم تتطابق بيانات الدفع مع قيمة الاشتراك."},409);
  const code=licenseKey(),hash=await sha256(code),licenseId=crypto.randomUUID(),clinicId=crypto.randomUUID(),membershipId=crypto.randomUUID(),expiryDate=new Date();if(payment.term==="annual")expiryDate.setFullYear(expiryDate.getFullYear()+1);else expiryDate.setMonth(expiryDate.getMonth()+1);const expiry=expiryDate.toISOString(),now=new Date().toISOString();
  await db.batch([db.prepare("UPDATE subscriptions SET payment_status='paid',paid_amount_ils=?,payment_reference=?,paid_at=CURRENT_TIMESTAMP WHERE id=? AND payment_status='pending'").bind(payment.amount_ils,payment.payment_reference,payment.subscription_id),db.prepare("INSERT INTO licenses (id,subscription_id,key_hash,key_hint,status,expires_at) SELECT ?,?, ?,?,'issued',? WHERE changes()>0").bind(licenseId,payment.subscription_id,hash,code.slice(-4),expiry),db.prepare("INSERT INTO clinics (id,name,owner_user_id,license_id) SELECT ?,?,?,? WHERE EXISTS (SELECT 1 FROM licenses WHERE id=? AND subscription_id=?) AND NOT EXISTS (SELECT 1 FROM clinics WHERE owner_user_id=?)").bind(clinicId,payment.clinic_name,user.userId,licenseId,licenseId,payment.subscription_id,user.userId),db.prepare("INSERT INTO clinic_memberships (id,clinic_id,user_id,email,role) SELECT ?,?,?,?,'clinic_admin' WHERE EXISTS (SELECT 1 FROM clinics WHERE id=? AND owner_user_id=? AND license_id=?)").bind(membershipId,clinicId,user.userId,user.email,clinicId,user.userId,licenseId),db.prepare("UPDATE licenses SET status='active',clinic_id=?,activated_at=? WHERE id=? AND status='issued' AND EXISTS (SELECT 1 FROM clinic_memberships WHERE clinic_id=? AND user_id=? AND role='clinic_admin')").bind(clinicId,now,licenseId,clinicId,user.userId),db.prepare("UPDATE qredit_subscription_payments SET status='paid',provider_status='PAID',paid_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND EXISTS (SELECT 1 FROM licenses WHERE id=? AND status='active')").bind(payment.id,licenseId),db.prepare("INSERT INTO audit_logs (id,clinic_id,actor_user_id,action,resource_type,resource_id) SELECT ?,?,?, 'subscription.qredit_paid','subscription',? WHERE EXISTS (SELECT 1 FROM licenses WHERE id=? AND status='active')").bind(crypto.randomUUID(),clinicId,user.userId,payment.subscription_id,licenseId)]);
  const active=await db.prepare("SELECT c.id FROM clinics c JOIN licenses l ON l.id=c.license_id WHERE c.owner_user_id=? AND l.status='active' AND l.expires_at>? ORDER BY c.created_at DESC LIMIT 1").bind(user.userId,now).first();if(!active)return response({error:"اكتمل التحقق من الدفع، لكن تعذر تفعيل حساب العيادة تلقائيًا. تواصل مع إدارة البرنامج."},409);return response({status:"paid",activated:true,clinicName:payment.clinic_name});
 }catch{return response({error:"تعذر التحقق من الدفع الآن. أعد المحاولة بعد قليل."},502);}
}
